SELECT
	COMP, CUST, BANK, INV, CUSPO, IDAT, DDAT, X.PERD, ACCT, DHCURR, TERM, DESCR, SUM(DUE) DUE
FROM
	(
	SELECT
		ASITYP||' - '||ASTRTP TP, 
		CHAR(ASIDAT) AS IDAT, 
		CHAR(ASDDAT) AS DDAT,
		ASCOMP COMP, 
		ASCUST||' - '||RTRIM(BVNAME) CUST, 
		BVARCD BANK, 
		LTRIM(RTRIM(ASINV#)) AS INV, 
		ASCPON CUSPO,  
		ASDUAM DUE, 
		DIGITS(ASFSYR)||DIGITS(ASFSPR) AS PERD, 
		ASCOM#||ASARAC ACCT
	FROM
		LGDAT.AROPH AROP
		INNER JOIN LGDAT.CUST ON
			BVCUST = ASCUST
	WHERE
		DIGITS(ASFSYR)||DIGITS(ASFSPR) <= '1604' AND 
		ASDUAM <> 0 AND ASCOMP IN ('36','39')

	UNION ALL

	SELECT
		LOTTYP||' - '||LOTRTP TP,
		CHAR(ASIDAT) IDAT,
		CHAR(ASDDAT) DDAT,
		LOCOMP COMP,
		LOCUST||' - '||RTRIM(BVNAME) CUST,
		BVARCD BANK,
		RTRIM(LOINV#) INV, 
		ASCPON CUSPO,
		-LOAMT DUE,
		DIGITS(ASFSYR)||DIGITS(ASFSPR) AS PERD,
		ASCOM#||ASARAC ACCT
	FROM
		LGDAT.ARTRN
		INNER JOIN LGDAT.CUST ON
			BVCUST = LOCUST
		LEFT OUTER JOIN LGDAT.AROPH ON
			LOCOM# = ASCOM# AND
			LOCUST = ASCUST AND
			LOINV# = ASINV#
			
	WHERE
		DIGITS(LOFSYR)||DIGITS(LOFSPR) > '1604' AND
		DIGITS(ASFSYR)||DIGITS(ASFSPR) <= '1604' AND LOCOMP IN ('36','39')
	) X
	LEFT OUTER JOIN LGDAT.OIH ON	
		DHINV# = INV
	LEFT OUTER JOIN FANALYSIS.VW_FFTMCD ON
		TERM = DHTRCD
	LEFT OUTER JOIN FANALYSIS.FFCRET C ON	
		FCUR = DHCURR AND
		TCUR = 'US' AND
		RTYP = 'ME' AND
		C.PERD = '1604'
GROUP BY
	COMP, CUST, BANK, INV, CUSPO, IDAT, DDAT, X.PERD, ACCT, DHCURR, TERM, DESCR