SELECT
	VERSION,
	CHAN,
	GEO,
	ACCOUNT,
	GLEC,
	SUBSTR(DIGITS(YEAR(B_ORDERDATE)),9)||SUBSTR(DIGITS(MONTH(B_ORDERDATE)),9) ORDERDATE,
	SUBSTR(DIGITS(YEAR(B_REQUESTDATE)),9)||SUBSTR(DIGITS(MONTH(B_REQUESTDATE)),9) REQUESTDATE,
	SUBSTR(DIGITS(YEAR(B_SHIPDATE)),9)||SUBSTR(DIGITS(MONTH(B_SHIPDATE)),9) SHIPDATE,
	SUM(FB_VAL_USD) AMOUNT
FROM
	QGPL.FFOTEST
WHERE
	SUBSTR(GLEC,1,1) IN ('1','2')
GROUP BY
	VERSION,
	CHAN,
	GEO,
	ACCOUNT,
	GLEC,
	SUBSTR(DIGITS(YEAR(B_ORDERDATE)),9)||SUBSTR(DIGITS(MONTH(B_ORDERDATE)),9),
	SUBSTR(DIGITS(YEAR(B_REQUESTDATE)),9)||SUBSTR(DIGITS(MONTH(B_REQUESTDATE)),9),
	SUBSTR(DIGITS(YEAR(B_SHIPDATE)),9)||SUBSTR(DIGITS(MONTH(B_SHIPDATE)),9)
ORDER BY
	VERSION,
	CHAN,
	GEO,
	ACCOUNT,
	GLEC,
	SUBSTR(DIGITS(YEAR(B_ORDERDATE)),9)||SUBSTR(DIGITS(MONTH(B_ORDERDATE)),9),
	SUBSTR(DIGITS(YEAR(B_REQUESTDATE)),9)||SUBSTR(DIGITS(MONTH(B_REQUESTDATE)),9),
	SUBSTR(DIGITS(YEAR(B_SHIPDATE)),9)||SUBSTR(DIGITS(MONTH(B_SHIPDATE)),9)