
  
CREATE FUNCTION RLARP.FN_ISB ( vPERD varchar(4) ) 
	RETURNS TABLE
	( 
		PERD VARHCAR(4),
		ACCT VARCHAR(12),
		TRANS FLOAT,
		GLMT FLOAT,
		DIFF FLOAT
	)
	LANGUAGE SQL 
	SPECIFIC RLARP.FN_CONSH 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   

	/*
	This functino adds up the transactions in FFSBGLR1 and makes sure they match the GLMT file net transactions listed
	*/

	BEGIN 
	
	RETURN 
	SELECT
		PERD, ACCT, SUM(TRANS) TRANS, SUM(GLMT) GLMT, SUM(TRANS)-SUM(GLMT) DIFF
	FROM
		(
		SELECT
			'GLMT' SRCE, FSPR PERD, ACCOUNT ACCT, 0 TRANS, NETT GLMT
		FROM 
			RLARP.VW_FFTB
		WHERE
			FSPR = vPERD
		

		UNION ALL

		SELECT
			'TRANS' SRCE, PERD, ACCT, SUM(AMT) TRANS, 0 GLMT
		FROM
			RLARP.FFSBGLR1
		WHERE
			PERD = vPERD AND
			MODULE  <> 'APVM'
		GROUP BY
			PERD, ACCT
		) X
	GROUP BY
		PERD, ACCT
	HAVING
		ABS(ROUND(SUM(TRANS)-SUM(GLMT),0)) > 1;

	END;