WITH
	-------MI & MN are intermediate tables used to build final intermediate table SM which lists reps & managers-----
	MI
	(
		GRP,
		CODE
	)
	AS
	(
		SELECT 
			SUBSTR(LTRIM(RTRIM(A9)),1,3),
			MIN(A9)
		FROM
			LGDAT.CODE
		WHERE
			A2 = 'MM'
		GROUP BY
			SUBSTR(LTRIM(RTRIM(A9)),1,3)
	),
	MN(GRP, CODE, DESCR)
	AS
	(
		SELECT
			GRP, 
			CODE,
			A30 DESCR
		FROM
			MI
			INNER JOIN LGDAT.CODE ON
				A2 = 'MM' AND
				A9 = CODE
	),
	SM(DIRECTOR, RCODE, REPP)
	AS
	(
		SELECT
			MN.GRP ||' - ' ||DESCR DIRECTOR,
			LTRIM(RTRIM(A9)) RCODE,
			LTRIM(RTRIM(A9)) ||' - ' ||A30 REPP
		FROM
			LGDAT.CODE
			INNER JOIN MN ON
				GRP = SUBSTR(LTRIM(RTRIM(A9)),1,3)
		WHERE
			A2 = 'MM'
	),
	----build dates tables------------
	GLPD (
	COMP, 
	FSYR, 
	PERDS, 
	PERD, 
	FSPR, 
	SDAT, 
	EDAT, 
	CAPR, 
	NDAYS
	) AS (
		SELECT 
			N1COMP COMP, N1CCYY FSYR, KPMAXP PERDS, DIGITS(N1FSPP) PERD, 
			DIGITS(N1FSYP) FSPR,  
			N1SD01 SDAT, N1ED01 EDAT, 
			SUBSTR(CHAR(N1ED01),3,2)||SUBSTR(CHAR(N1ED01),6,2) CAPR,  
			N1ED01 - N1SD01 +1 NDAYS 
		  
		FROM 
			LGDAT.GLDATREF 
			INNER JOIN LGDAT.GLDATE ON 
				KPCOMP = N1COMP AND 
				KPCCYY = N1CCYY
	),
	-------now build out initial orders list first (since it is a cross join and needs filtered before doing more joins)---
	 O (
		FLAG, 
		CALC_STATUS, 
		DDORD#, 
		DDITM#, 
		FGBOL#, 
		FGENT#, 
		DIINV#, 
		DILIN#, 
		DCODAT, 
		DDQDAT,
		DCMDAT,
		FESDAT, 
		FESIND, 
		DHIDAT, 
		DHPOST, 
		FSPR_INV,
		PLNT,
		CUST_BILL,
		CUST_SHIP,
		GL_CODE, 
		PART,
		PROMO,
		DCPO,
		RETURN_REAS,
		TERMS,
		FB_QTY,
		CURRENCY,
		FB_VAL_LOC
	) AS (

		SELECT
			------------------------status-------------------------------------------------------------------------
			F.FLAG, 
			CASE DDITST 
				WHEN 'C' THEN 
					CASE DDQTSI 
						WHEN 0 THEN 'CANCELED' 
						ELSE 'CLOSED' 
					END 
				ELSE 
					CASE F.FLAG
						WHEN 'SHIPMENT' THEN 'CLOSED' 
						ELSE CASE WHEN DDQTSI >0 THEN 'BACKORDER' ELSE 'OPEN' END 
					END 
			END CALC_STATUS, 
			-----------------------id's and flags------------------------------------------------------------------
			DDORD#, 
			DDITM#, 
			FGBOL#, 
			FGENT#, 
			DIINV#, 
			DILIN#, 
			DCODAT, 
			DDQDAT,
			DCMDAT,
			FESDAT, 
			FESIND, 
			DHIDAT, 
			DHPOST, 
			------------------------periods------------------------------------------------------------------------
			DIGITS(DHARYR)||DIGITS(DHARPR) FSPR_INV,
			------------------------attributes---------------------------------------------------------------------
			COALESCE(DHPLNT,FGPLNT,SUBSTR(DDSTKL,1,3)) PLNT,
			COALESCE(DCBCUS,DHBCS#) CUST_BILL,
			COALESCE(DCSCUS,DHSCS#) CUST_SHIP,
			COALESCE(DIGLCD, DDGLC) GL_CODE, 
			COALESCE(DIPART,DDPART) PART,
			RTRIM(DCPROM) PROMO,
			DCPO,
			DDCRRS RETURN_REAS,
			COALESCE(DHTRCD,DCTRCD) TERMS,
			CASE F.FLAG
				WHEN 'REMAINDER' THEN 
					DDQTOI-DDQTSI
				WHEN 'SHIPMENT' THEN
					FGQSHP*CASE FESIND WHEN 'Y' THEN 1 ELSE 0 END
			END FB_QTY,
			COALESCE(DHCURR,DCCURR) CURRENCY,
			CASE F.FLAG
				WHEN 'REMAINDER' THEN 
					--------remaining qty*calculated price per---------
					CASE DDQTOI 
						WHEN 0 THEN 0 
						ELSE DDTOTI/DDQTOI 
					END*(DDQTOI - DDQTSI)
				WHEN 'SHIPMENT' THEN
					---------BOL quantity * calculated price per-------
					CASE DDQTOI 
						WHEN 0 THEN 0 
						ELSE DDTOTI/DDQTOI 
					END*COALESCE(FGQSHP*CASE FESIND WHEN 'Y' THEN 1 ELSE 0 END,DDQTSI)
			END FB_VAL_LOC
		FROM
			----------------------Order Data-----------------------------
			LGDAT.OCRI 
			INNER JOIN LGDAT.OCRH ON 
				DCORD# = DDORD# 
			-----------------------BOL-----------------------------------
			LEFT OUTER JOIN LGDAT.BOLD ON 
				FGORD# = DDORD# AND 
				FGITEM = DDITM# 
			LEFT OUTER JOIN LGDAT.BOLH ON 
				FEBOL# = FGBOL#
			----------------------Invoicing------------------------------
			LEFT OUTER JOIN LGDAT.OID ON 
				DIINV# = FGINV# AND 
				DILIN# = FGLIN# 
			LEFT OUTER JOIN LGDAT.OIH ON 
				DHINV# = DIINV# 
			CROSS JOIN TABLE( VALUES
				('REMAINDER'),
				('SHIPMENT')
			) AS F(FLAG)
		WHERE
			DCODAT >= '2016-06-01' AND
			(	
				(F.FLAG = 'REMAINDER' AND DDQTOI-DDQTSI <> 0) OR 
				(F.FLAG = 'SHIPMENT' AND FGQSHP*CASE FESIND WHEN 'Y' THEN 1 ELSE 0 END<>0)
			)
	)
SELECT
	--order data
	PLNT,
	DDORD# "ORDER",
	DDITM# ORDERITEM,
	FGBOL# BOL,
	FGENT# BOLITEM,
	DIINV# INVOICE,
	DILIN# INVOICEITEM,
	PROMO,
	RETURN_REAS,
	TERMS,
	CURRENCY,
	DCPO CUSTPO,
	DCODAT ORDERDATE,
	DDQDAT REQUESTDATE,
	DCMDAT PROMISEDATE,
	
	--customer data (bill-to)
	BC.BVCOMP BILLREMITTO,
	BC.BVCLAS BILLCUSTCLASS, 
	BC.BVCUST||' - '||RTRIM(BC.BVNAME) BILLCUST, 
	BC.BVSALM BILLREP,
	BR.REPP BILL_DSM,
	BR.DIRECTOR BILL_DIRECTOR,
	SC.BVCLAS SHIP_CUSTCLASS, 
	SC.BVCUST||' - '||RTRIM(SC.BVNAME) SHIPCUST,
	SR.REPP SHIP_DSM,
	SR.DIRECTOR SHIP_DIRECTOR,

	--scenario (offline data)
	--COALESCE(CG.CGRP,BC.BVNAME) ACCOUNT,
	--COALESCE(T.GEO,'UNDEFINED') GEO, 
	--COALESCE(C.CHAN,'UNDEFINED') CHAN,
	
	--location
	QZCRYC ORIG_CTRY,
	QZPROV ORIG_PROV,
	SUBSTRING(QZPOST,1,3) ORIG_LANE,
	QZPOST ORIG_POST,
	SC.BVCTRY DEST_CTRY,
	SC.BVPRCD DEST_PROV,
	SUBSTRING(SC.BVPOST,1,3) DEST_LANE,
	SC.BVPOST DEST_POST,
	
	--item data
	
	PART,
	GL_CODE,
	COALESCE(AVMAJG,AWMAJG)||' - '||RTRIM(BQDES) MAJG,  
	COALESCE(AVMING,AWMING)||' - '||RTRIM(BRDES) MING,  
	COALESCE(AVMAJS,AWMAJS)||' - '||RTRIM(MS.BSDES1) MAJS,  
	COALESCE(AVMINS,AWMINS)||' - '||RTRIM(NS.BSDES1) MINS,  
	COALESCE(AVGLCD,AWGLDC)||' - '||RTRIM(GD.A30) GLDC,  
	COALESCE(AVGLED,AWGLED)||' - '||RTRIM(GE.A30) GLEC, 
	COALESCE(AVHARM, AWHARM) HARM,  
	COALESCE(AVCLSS,AWCLSS) CLSS,  
	SUBSTR(AVCPT#,1,1) BRAND, 
	COALESCE(AVASSC,AWASSC) ASSC,
	FB_QTY, 							--flag basis quantity
	FB_VAL_LOC,							--flag basis value
	O.FB_VAL_LOC*RATE FB_VAL_USD,		--flag basis flag basis value USD
	FLAG,								--flag
	CALC_STATUS					
FROM
	O
	LEFT OUTER JOIN LGDAT.STKMM ON
		AVPART = PART
	LEFT OUTER JOIN LGDAT.STKMP ON
		AWPART = PART
	LEFT OUTER JOIN LGDAT.MAJG ON  
		BQGRP = AVMAJG  
	LEFT OUTER JOIN LGDAT.MMSL MS ON  
		MS.BSMJCD = COALESCE(AVMAJS, AWMAJS) AND  
		MS.BSMNCD = ''  
	LEFT OUTER JOIN LGDAT.MMSL NS ON  
		NS.BSMJCD = COALESCE(AVMAJS, AWMAJS) AND  
		NS.BSMNCD = COALESCE(AVMINS, AWMINS)
	LEFT OUTER JOIN LGDAT.MMGP ON  
		BRGRP = COALESCE(AVMAJG, AWMAJG) AND  
		BRMGRP = COALESCE(AVMING, AWMING)
	LEFT OUTER JOIN LGDAT.CODE GE ON  
		RTRIM(LTRIM(GE.A9)) =COALESCE(AVGLED, AWGLED) AND  
		GE.A2 = 'GE'  
	LEFT OUTER JOIN LGDAT.CODE GD ON  
		RTRIM(LTRIM(GD.A9)) = COALESCE(AVGLCD, AWGLDC) AND  
		GD.A2 = 'EE'  
	LEFT OUTER JOIN LGDAT.PLNT ON	
		YAPLNT = PLNT
	LEFT OUTER JOIN LGDAT.ADRS ON
		QZADR = YAADR#
	LEFT OUTER JOIN GLPD GP ON
		GP.COMP = YACOMP AND
		GP.FSPR = FSPR_INV
	LEFT OUTER JOIN GLPD GF ON
		GF.COMP = YACOMP AND
		GF.SDAT <= DCODAT AND
		GF.EDAT >= DCODAT
	LEFT OUTER JOIN RLARP.FFCRET X ON
		X.PERD = COALESCE(FSPR_INV, GF.FSPR) AND
		X.FCUR = CURRENCY AND	
		X.TCUR = 'US' AND
		X.RTYP = 'MA'
	LEFT OUTER JOIN LGDAT.CUST BC ON
		BC.BVCUST = CUST_BILL
	LEFT OUTER JOIN LGDAT.CUST SC ON
		SC.BVCUST = CUST_SHIP
	LEFT OUTER JOIN SM SR ON
		SR.RCODE = SC.BVSALM
	LEFT OUTER JOIN SM BR ON
		BR.RCODE = BC.BVSALM