SELECT
	MODULE, BATCH, PERD, TDATE, PDATE, ACCT, 
	SUM(AMT) AMT,
	PROJ, USRN, REV, CUSMOD, CUSKEY1, CUSKEY1D, CUSKEY2, CUSKEY2D, CUSKEY3, CUSKEY3D, CUSKEY4, CUSKEY4D, CUSVEND, CUSCUST, RECID
FROM
	(
	SELECT
		DKSRCE||DKQUAL AS MODULE, 
		DIGITS(DKBTC#) AS BATCH,
		DIGITS(DKFSYY)||DIGITS(DKFSPR) PERD,
		CHAR(DKTDAT) AS TDATE, 
		CHAR(DKPDAT) AS PDATE, 
		DIGITS(DKACC#) AS ACCT, 
		CASE WHEN PPV_DET IS NULL
			THEN DKAMT
			ELSE ROUND(DKAMT*PPV_DET,2)
		END AMT,
		DKPJNM AS PROJ, 
		DKFUT4 AS USRN,
		DKREV AS REV,
		'VOUCHER POSTING' CUSMOD,
		DKKEYN AS CUSKEY1, 
		'VOUCHER NUMBER' AS CUSKEY1D, 
		IDINV# AS CUSKEY2, 
		'INVOICE' AS CUSKEY2D, 
		CASE WHEN PPV_DET IS NULL THEN IDVDES ELSE DIGITS(LBRKEY) END AS CUSKEY3,
		CASE WHEN PPV_DET IS NULL THEN 'DESCR' ELSE 'RKEY' END AS CUSKEY3D,
		LBPT# AS CUSKEY4,
		CASE WHEN COALESCE(LBPT#,'') = ''  THEN '' ELSE 'PART' END AS CUSKEY4D,
		IDVEN# AS CUSVEND,
		'' AS CUSCUST, 
		DIGITS(DKRCID) AS RECID
	FROM
		LGDAT.GLSBAP
		LEFT OUTER JOIN LGDAT.VCHR ON
			IDCOM# = SUBSTR(DKACC#,1,2) AND
			IDVCH# = DKKEYN AND
			IDFISY = DKFSYY AND
			IDFISP = DKFSPR
			--an assumption is that given a fiscal period all voucher numbers are different, however this could be violated due to bank codes
			--not being differentiated on the ledger and the account code may not reflect the bank code granularity and there is no history
			--file on the bank master data so it doesn't matter anyways
		LEFT OUTER JOIN
		(
			SELECT
				X.COMP COMP, X.VCHR VCHR, X.ACCT ACCT, X.PPV PPV, X.CNT CNT, X.TOT TOT, LBRKEY, LBPT#, LBEXT, LBCOM#||Y1PRVR PPVACCT, LBPPV, 
				CASE X.PPV 
					WHEN 0 THEN 
						CASE X.TOT
							WHEN 0 THEN FLOAT(1)/FLOAT(X.CNT)
							ELSE LBEXT/X.TOT 
						END
					ELSE LBPPV/X.PPV
				END PPV_DET
			FROM	
				LGDAT.POMVAR
				LEFT OUTER JOIN LGDAT.STKMM ON
					AVPART = LBPT#
				LEFT OUTER JOIN LGDAT.STKMP ON
					AWPART = LBPT#
				LEFT OUTER JOIN LGDAT.GLIE ON
					Y1PLNT = LBPLNT AND
					Y1GLEC = COALESCE(AVGLED, AWGLED)
				LEFT OUTER JOIN LGDAT.POI ON
					KBPO# = LBPO# AND
					KBITM# = LBPOI#
				LEFT OUTER JOIN
				(
					SELECT
						LBCOM# COMP, LBVCH# VCHR, 
						LBCOM#||COALESCE(Y1PRVR,KBGL#) ACCT, --if the ppv account is null, then use the expense account from the PO
						SUM(LBPPV) PPV, COUNT(LBRKEY) CNT, SUM(LBEXT) TOT
					FROM	
						LGDAT.POMVAR
						LEFT OUTER JOIN LGDAT.STKMM ON
							AVPART = LBPT#
						LEFT OUTER JOIN LGDAT.STKMP ON
							AWPART = LBPT#
						LEFT OUTER JOIN LGDAT.GLIE ON
							Y1PLNT = LBPLNT AND
							Y1GLEC = COALESCE(AVGLED, AWGLED)
						LEFT OUTER JOIN LGDAT.POI ON
							KBPO# = LBPO# AND
							KBITM# = LBPOI#
							
					WHERE
						LBFSYY = 'YY' AND
						LBFSPP = 'PP'
						--may need to consider excluding .00001 cost items
					GROUP BY
						LBCOM#, LBVCH#, LBCOM#||COALESCE(Y1PRVR,KBGL#)
				) X ON
					X.COMP = LBCOM# AND	
					X.VCHR = LBVCH# AND
					X.ACCT = LBCOM#||COALESCE(Y1PRVR,KBGL#)
			WHERE
				LBFSYY = 'YY' AND
				LBFSPP = 'PP'
		) SPLIT ON	
			SPLIT.COMP = SUBSTR(DKACC#,1,2) AND	
			SPLIT.VCHR = DKKEYN AND
			SPLIT.ACCT = DKACC#
	WHERE
		DKSRCE = 'AP' AND
		DKQUAL = 'VN' AND
		DKFSYR = 20 AND  
		DKFSYY = 'YY' AND
		DKFSPR = 'PP'
	) AGG
GROUP BY
	MODULE, BATCH, PERD, TDATE, PDATE, ACCT, 
	PROJ, USRN, REV, CUSMOD, CUSKEY1, CUSKEY1D, CUSKEY2, CUSKEY2D, CUSKEY3, CUSKEY3D, CUSKEY4, CUSKEY4D, CUSVEND, CUSCUST, RECID
		
