
SELECT
	FSYR,
	QRTR,
	SHP_PERD PERD,
	O.PLNT, O.PART, BCUS, SCUS,
	CURR, 'ORD' INV_TYPE,
	GLDC, GLEC, MAJG, MING, MAJS, MINS, BVCLAS BILL_CLASS,
	'GROSS',
	SUM(QTY) QTY,
	SUM(QTY*TOT) EXT_COST,
	SUM(QTY*TOT*CASE SUBSTR(O.PLNT,1,2) WHEN '11' THEN .74074 ELSE 1 END) EXT_COST_USD,
	SUM(VALUE) VALUE,
	SUM(VALUE*CASE CURR WHEN 'CA' THEN .74074 ELSE 1 END) VALUE_USD
FROM
	FANALYSIS.FFFORD O
	LEFT OUTER JOIN FANALYSIS.VW_FFITEMM ON
		ITEM = O.PART
	LEFT OUTER JOIN QGPL.FFICSTX C ON
		C.PART = O.PART AND
		C.PLNT = O.PLNT AND
		TRI = 'STD'
	LEFT OUTER JOIN LGDAT.CUST ON
		BVCUST = BCUS
	LEFT OUTER JOIN FANALYSIS.FFPERD ON
		FSPR = SHP_PERD
WHERE
	SHP_PERD >= '1601' AND
	SHP_PERD <= '1612'
GROUP BY
	FSYR,
	QRTR,
	SHP_PERD,
	O.PLNT,O.PART, BCUS, SCUS,
	CURR,
	GLDC, GLEC, MAJG, MING, MAJS, MINS, BVCLAS