CREATE VIEW RLARP.vARFLCS 
(
	COMP, PLNT, ACC, PRIME, AZTITL, INACTIVE, GLCC, ELIM_TYPE, ELIM_REL, ELIM_DFGRP, ELIM_CO,
	FSPR, CAPR, SDAT, EDAT, FGRP, STMT, LVL0, LVL1, LVL2, LVL3, 
	MODULE, CUSMOD, CUSKEY1, CUSKEY1D, CUSKEY2, CUSKEY2D, CUSKEY3, CUSKEY3D, CUSKEY4, CUSKEY4D,
	EBITDA, DEPARTMENT, DEP_GRP, CURR, COMPONENT, AMOUNT, AMOUNT
)
AS

SELECT  
	*
FROM 	  
	RLARP.VW_GLLCS
WHERE MODULE <> 'APVM'

UNION ALL

SELECT 
	COMP, PLNT, ACC, PRIME,AZTITL, INACTIVE, GLCC, ELIM_TYPE, ELIM_REL, ELIM_DFGRP, ELIM_CO, FSPR, CAPR, SDAT, EDAT, 
	FGRP, STMT, LVL0, LVL1, LVL2, LVL3, 
	'' MODULE,
	'' CUSMOD,
	'' CUSKEY1, '' CUSKEY1D, 
	'' CUSKEY2, '' CUSKEY2D, 
	'' CUSKEY3, '' CUSKEY3D, 
	'' CUSKEY4, '' CUSKEY4D,
	EBITDA, DEPARTMENT, DEP_GRP,
	CURR,
	'OPEN' COMPONENT,
	ROUND(USD_OPEN,2) AMOUNT
FROM 
	RLARP.VW_FFTBLCS 
WHERE 
	COMP > '19'

UNION ALL

SELECT 
	COMP, PLNT, ACC, PRIME,AZTITL, INACTIVE, GLCC, ELIM_TYPE, ELIM_REL, ELIM_DFGRP, ELIM_CO, FSPR, CAPR, SDAT, EDAT, 
	FGRP, STMT, LVL0, LVL1, LVL2, LVL3, 
	'' MODULE,
	'' CUSMOD,
	'' CUSKEY1, '' CUSKEY1D, 
	'' CUSKEY2, '' CUSKEY2D, 
	'' CUSKEY3, '' CUSKEY3D, 
	'' CUSKEY4, '' CUSKEY4D,
	EBITDA, DEPARTMENT, DEP_GRP,
	CURR,
	'END' COMPONENT,
	ROUND(USD_END,2) AMOUNT
FROM 
	RLARP.VW_FFTBLCS 
WHERE 
	COMP > '19'

UNION ALL

SELECT 
	B.COMP, PLNT, ACC, PRIME,AZTITL, INACTIVE, GLCC, ELIM_TYPE, ELIM_REL, ELIM_DFGRP, ELIM_CO,FSPR, CAPR, SDAT, EDAT, 
	FGRP, STMT, LVL0, LVL1, LVL2, LVL3, 
	'' MODULE,
	'' CUSMOD,
	'' CUSKEY1, '' CUSKEY1D, 
	'' CUSKEY2, '' CUSKEY2D, 
	'' CUSKEY3, '' CUSKEY3D, 
	'' CUSKEY4, '' CUSKEY4D,
	EBITDA, DEPARTMENT, DEP_GRP,
	CURR,
	'FX' COMPONENT,
	ROUND(USD_OPEN - OPEN_LOCAL*XP.RATE,2) AMOUNT
FROM 
	RLARP.VW_FFTBLCS B
	INNER JOIN RLARP.VW_PRFSPR P ON
		P.COMP = B.COMP AND
		P.CURRP = B.FSPR
	LEFT OUTER JOIN RLARP.FFCRET XP ON 
		XP.FCUR = B.CURR AND
		XP.TCUR = 'US' AND
		XP.PERD = P.PRIORP AND
		XP.RTYP = CASE WHEN SUBSTR(FGRP,1,1) <= '3' THEN 'ME' ELSE 'MA' END
WHERE 
	B.COMP > '19'