SELECT
	PERD, NWPLNT, ADEPT, ARESC, PART, STAT, RPLN, OPTR, SDEPT, SRESC, RRATE, 
	SUM(OAQTYG) QTYG,
	SUM(OAQTYS) QTYS,
	SUM(STIME) STIME,
	SUM(STIMEG) STIMEG,
	SUM(RTIME) RTIME,
	SUM(DTIME) DTIME,
	SUM(CASE SUBSTR(CODE,1,2) WHEN 'B2' THEN DTIME ELSE 0 END) PDTIME,
	SUM(ABSLAB) ABSLAB,
	SUM(ABSOVH) ABSOVH,
	CODE, 
	SUM(FPV) FPV
FROM
(
-----------------------------DOWNTIME--------------------------------------------
SELECT
	NWFSYY||DIGITS(NWFSPP) PERD, NWPLNT, NXDEPT ADEPT, NXRESC ARESC, '' PART, '' STAT, '' RPLN, 0 OPTR, '' SDEPT, '' SRESC, 
	0 RRATE, 
	0 OAQTYG, 0 OAQTYS,
	0 STIME,
	0 STIMEG,
	0 RTIME,
	SUM(NXTIME) DTIME,
	0 ABSLAB,
	0 ABSOVH,
	RTRIM(NXINDC)||' - '||RTRIM(AFDES1) CODE, 0 FPV
FROM
	LGDAT.RPRH 
	INNER JOIN LGDAT.RPRD ON
		NWBTID = NXBTID
	LEFT OUTER JOIN LGDAT.INDLBR ON
		AFCODE = NXINDC
WHERE
	NWFSYY >= 17
GROUP BY
	NWFSYY||DIGITS(NWFSPP), NWPLNT, NXDEPT, NXRESC,RTRIM(NXINDC)||' - '||RTRIM(AFDES1)

UNION ALL

--------------------------------RUN TIME----------------------------------------
SELECT
	NWFSYY||DIGITS(NWFSPP) PERD, NWPLNT, OADEPT ADEPT, OARESC ARESC, OAPART PART, V6STAT STAT, V6RPLN RPLN, V6OPTR OPTR,AODEPT SDEPT, AORESC SRESC,
	CASE ABVBRD WHEN 0 THEN IFNULL(AAVBRD,0) ELSE IFNULL(ABVBRD,0) END+CASE ABBRDR WHEN 0 THEN IFNULL(AABRDR,0) ELSE IFNULL(ABBRDR,0) END RRATE,
	0 OAQTYG, 0 OAQTYS,
	0 STIME,
	0 STIMEG,
	SUM(OATIME) RTIME, 
	0 DTIME,
	0 ABSLAB, 0 ABSOVH,
	'02 - RUN' CODE, 0 FPV
FROM
	LGDAT.RPRR
	INNER JOIN LGDAT.RPRH ON
		NWBTID = OABTID
	LEFT OUTER JOIN LGDAT.METHDR ON
		AOPART = OAPART AND
		AOPLNT = NWPLNT AND
		AOSEQ# = OASEQ#
	LEFT OUTER JOIN LGDAT.PUNIT C1 ON
  		C1.IHPART = OAPART AND
   		C1.IHUNT2 = OAUNIT AND
   		C1.IHUNT1 = AOUNIT
  	LEFT OUTER JOIN LGDAT.PUNIT C2 ON
   		C2.IHPART = OAPART AND
   		C2.IHUNT1 = OAUNIT AND
   		C2.IHUNT2 = AOUNIT
	LEFT OUTER JOIN LGDAT.RESRE ON
   		ABDEPT = AODEPT AND
   		ABRESC = AORESC
  	LEFT OUTER JOIN LGDAT.DEPTS ON
   		ABDEPT = AADEPT
	LEFT OUTER JOIN LGDAT.STKA ON
		V6PART = OAPART AND
		V6PLNT = NWPLNT
WHERE
	NWFSYY >= 17
GROUP BY
	NWFSYY||DIGITS(NWFSPP), NWPLNT, OADEPT, OARESC, OAPART, AORESC, AODEPT,V6STAT, V6RPLN, V6OPTR,
	CASE ABVBRD WHEN 0 THEN IFNULL(AAVBRD,0) ELSE IFNULL(ABVBRD,0) END+CASE ABBRDR WHEN 0 THEN IFNULL(AABRDR,0) ELSE IFNULL(ABBRDR,0) END

UNION ALL

-------------------------------------EARNED HOURS------------------------------------------------
SELECT
	NWFSYY||DIGITS(NWFSPP) PERD, NWPLNT, OADEPT ADEPT, OARESC ARESC, OAPART PART, V6STAT STAT, V6RPLN RPLN, V6OPTR OPTR, AODEPT SDEPT, AORESC SRESC,
	(
		CASE ABVBRD WHEN 0 THEN IFNULL(AAVBRD,0) ELSE IFNULL(ABVBRD,0) END+
		CASE ABBRDR WHEN 0 THEN IFNULL(AABRDR,0) ELSE IFNULL(ABBRDR,0) END
	) RRATE,
	SUM(OAQTYG) OAQTYG, 
	SUM(OAQTYS) OAQTYS,
	SUM(
		(CASE IFNULL(AORUNS,0) WHEN 0 THEN 0 ELSE 1/AORUNS END+AOSETP/1000000)*
		FLOAT(OAQTYG+OAQTYS)*
		COALESCE((C1.IHCNV1/C1.IHCNV2),(C2.IHCNV2/C2.IHCNV1),FLOAT(1))
	) STIME, 
	SUM(
		(CASE IFNULL(AORUNS,0) WHEN 0 THEN 0 ELSE 1/AORUNS END+AOSETP/1000000)*
		FLOAT(OAQTYG)*
		COALESCE((C1.IHCNV1/C1.IHCNV2),(C2.IHCNV2/C2.IHCNV1),FLOAT(1))
	) STIMEG, 
	0 RTIME,
	0 DTIME,
	SUM(
		CASE ABLABR WHEN 0 THEN IFNULL(AASTDR,0) ELSE IFNULL(ABLABR,0) END*
		(CASE IFNULL(AORUNS,0) WHEN 0 THEN 0 ELSE 1/AORUNS END*AO#MEN/AO#MCH+AOSETP*AOSCRW/1000000)*
		FLOAT(OAQTYG+OAQTYS)*
		COALESCE((C1.IHCNV1/C1.IHCNV2),(C2.IHCNV2/C2.IHCNV1),FLOAT(1))
	) ABSLAB,
	SUM(
		(CASE ABVBRD WHEN 0 THEN IFNULL(AAVBRD,0) ELSE IFNULL(ABVBRD,0) END+CASE IFNULL(ABBRDR,0) WHEN 0 THEN IFNULL(AABRDR,0) ELSE IFNULL(ABBRDR,0) END)*
		(CASE IFNULL(AORUNS,0) WHEN 0 THEN 0 ELSE 1/AORUNS END+AOSETP/1000000)*
		FLOAT(OAQTYG+OAQTYS)*
		COALESCE((C1.IHCNV1/C1.IHCNV2),(C2.IHCNV2/C2.IHCNV1),FLOAT(1))
	) ABSOVH,
	'01 - EARNED' CODE, 0 FPV
FROM
	LGDAT.RPRR
	INNER JOIN LGDAT.RPRH ON
		NWBTID = OABTID
	LEFT OUTER JOIN LGDAT.METHDR ON
		AOPART = OAPART AND
		AOPLNT = NWPLNT AND
		AOSEQ# = OASEQ#
	LEFT OUTER JOIN LGDAT.PUNIT C1 ON
  		C1.IHPART = OAPART AND
   		C1.IHUNT2 = OAUNIT AND
   		C1.IHUNT1 = AOUNIT
  	LEFT OUTER JOIN LGDAT.PUNIT C2 ON
   		C2.IHPART = OAPART AND
   		C2.IHUNT1 = OAUNIT AND
   		C2.IHUNT2 = AOUNIT
	LEFT OUTER JOIN LGDAT.RESRE ON
   		ABDEPT = AODEPT AND
   		ABRESC = AORESC
  	LEFT OUTER JOIN LGDAT.DEPTS ON
   		ABDEPT = AADEPT
	LEFT OUTER JOIN LGDAT.STKA ON
		V6PART = OAPART AND
		V6PLNT = NWPLNT
WHERE
	NWFSYY >= 17 AND
	AORESC <> ''
GROUP BY
	NWFSYY||DIGITS(NWFSPP), NWPLNT, OADEPT, OARESC, OAPART, AORESC, AODEPT,V6STAT, V6RPLN, V6OPTR,
	CASE ABVBRD WHEN 0 THEN IFNULL(AAVBRD,0) ELSE IFNULL(ABVBRD,0) END+CASE ABBRDR WHEN 0 THEN IFNULL(AABRDR,0) ELSE IFNULL(ABBRDR,0) END

UNION ALL

---------------------------------------------FPV-------------------------------------------

SELECT
	NWFSYY||DIGITS(NWFSPP) PERD , NWPLNT, TIDEPT ADEPT, TIRESC ARESC, TIPART PART,
	V6STAT STAT, V6RPLN RPLN, V6OPTR OPTR, '' SDEPT, '' SRESC,
	0 RRATE, 
	0 OAQTYG, 0 OAQTYS,
	0 STIME,
	0 STIMEG,
	0 RTIME,
	0 DTIME,
	0 ABSLAB,
	0 ABSOVH,
	'03 - FPV' CODE,
	SUM(TIQTYP*COALESCE((C1.IHCNV1/C1.IHCNV2),(C2.IHCNV2/C2.IHCNV1),FLOAT(1))*COALESCE(CHSTCS, CGSTCS, Y0STCS)) FPV
FROM
	LGDAT.RPRH
	INNER JOIN LGDAT.RPRQ ON
		TIBTID = NWBTID
	LEFT OUTER JOIN LGDAT.STKA ON
		V6PART = TIPART AND
		V6PLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.ICSTP ON
		CHPART = TIPART AND
		CHPLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.ICSTM ON
		CGPART = TIPART AND
		CGPLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.ICSTR ON
		Y0PART = TIPART AND
		Y0PLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.STKMM ON
		AVPART = TIPART
	LEFT OUTER JOIN LGDAT.STKMP ON
		AWPART = TIPART
	LEFT OUTER JOIN LGDAT.GLIE ON
		Y1GLEC = COALESCE(AWGLED, AVGLED) AND
		Y1PLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.PLNT ON
		YAPLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.PUNIT C1 ON
  		C1.IHPART = TIPART AND
   		C1.IHUNT2 = TIUNIT AND
   		C1.IHUNT1 = V6UNTI
  	LEFT OUTER JOIN LGDAT.PUNIT C2 ON
   		C2.IHPART = TIPART AND
   		C2.IHUNT1 = TIUNIT AND
   		C2.IHUNT2 = V6UNTI
WHERE
	NWFSYY >= 17 AND
	TIQTYP <> 0 AND
	SUBSTR(YACOMP||DIGITS(Y1INVA),7,4) = '1220'
GROUP BY
	NWFSYY||DIGITS(NWFSPP), NWPLNT, TIDEPT, TIRESC, TIPART,
	V6STAT, V6RPLN, V6OPTR

UNION ALL


SELECT
	NWFSYY||DIGITS(NWFSPP) PERD , NWPLNT NWPLNT, UIDEPT ADEPT, UIRESC ARESC, UIPART PART,
	V6STAT STAT, V6RPLN RPLN, V6OPTR OPTR, '' SDEPT, '' SRESC,
	0 RRATE, 
	0 OAQTYG, 0 OAQTYS,
	0 STIME,
	0 STIMEG,
	0 RTIME,
	0 DTIME,
	0 ABSLAB,
	0 ABSOVH,
	'03 - FPV' CODE,
	-SUM(UITQTY*CASE UIRQBY WHEN 'B' THEN -1 ELSE 1 END*COALESCE(CHSTCS, CGSTCS, Y0STCS)) FPV
FROM
	LGDAT.RPRH
	INNER JOIN LGDAT.RPRM ON
		UIBTID = NWBTID
	LEFT OUTER JOIN LGDAT.ICSTP ON
		CHPART = UIMTLP AND
		CHPLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.ICSTM ON	
		CGPART = UIMTLP AND
		CGPLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.ICSTR ON
		Y0PART = UIMTLP AND
		Y0PLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.STKMM ON
		AVPART = UIMTLP
	LEFT OUTER JOIN LGDAT.STKMP ON
		AWPART = UIMTLP
	LEFT OUTER JOIN LGDAT.GLIE ON
		Y1GLEC = COALESCE(AWGLED, AVGLED) AND
		Y1PLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.PLNT ON
		YAPLNT = NWPLNT
	LEFT OUTER JOIN LGDAT.STKA ON
		V6PART = UIPART AND
		V6PLNT = NWPLNT
WHERE
	NWFSYY >= 17 AND
	UITQTY <> 0 AND
	SUBSTR(YACOMP||DIGITS(Y1INVA),7,4) = '1220'
GROUP BY
	NWFSYY||DIGITS(NWFSPP), NWPLNT, UIDEPT, UIRESC, UIPART,
	V6STAT, V6RPLN, V6OPTR
) X

GROUP BY
	PERD, NWPLNT, ADEPT, ARESC, PART, STAT, RPLN, OPTR, SDEPT, SRESC, RRATE, CODE