SELECT
	V6PART,
	V6PLNT,
	V6STAT,
	V6RPLN,
	COALESCE(AVGLED, AWGLED) GLED,
	COALESCE(CGSTCS, CHSTCS, Y0STCS) AS CURCOST,
	COALESCE(CNSTCS, COSTCS, Y3STCS) AS FUTCOST,
	COALESCE(CNSTCS, COSTCS, Y3STCS) - COALESCE(CGSTCS, CHSTCS, Y0STCS) DIFF
FROM
	LGDAT.STKA
	LEFT OUTER JOIN LGDAT.STKMM ON
		AVPART = V6PART
	LEFT OUTER JOIN LGDAT.STKMP ON
		AWPART = V6PART
	LEFT OUTER JOIN LGDAT.ICSTP ON
		CHPART = V6PART AND
		CHPLNT = V6PLNT
	LEFT OUTER JOIN LGDAT.ICSTM ON
		CGPART = V6PART AND
		CGPLNT = V6PLNT
	LEFT OUTER JOIN LGDAT.ICSTR ON
		Y0PART = V6PART AND
		Y0PLNT = V6PLNT
	LEFT OUTER JOIN LGDAT.FTCSTP ON
		COPART = V6PART AND
		COPLNT = V6PLNT
	LEFT OUTER JOIN LGDAT.FTCSTM ON
		CNPART = V6PART AND
		CNPLNT = V6PLNT
	LEFT OUTER JOIN LGDAT.FTCSTR ON
		Y3PART = V6PART AND
		Y3PLNT = V6PLNT
WHERE	
	ABS(COALESCE(CNSTCS, COSTCS, Y3STCS) - COALESCE(CGSTCS, CHSTCS, Y0STCS)) > .00001
	