SELECT  
        V6PART,
        V6PLNT, 
        DESCR1, 
        SUBSTR(V6PART,1,8) MOLD, 
        STD_DATE, 
        STDCOST 
        /*
		V6PART, V6PLNT, V6STAT, V6RPLN, V6UNTI,  
		COALESCE(CGACCS, CHACCS, Y0ACCS) AS RECENTCOST,  
		CHAR(COALESCE(CGSDAT, CHSDAT, Y0SDAT)) STD_DATE,  
		COALESCE(CGSTCS, CHSTCS, Y0STCS) AS STDCOST,  
		COALESCE(CGMATS, CHSUC, Y0SMAT) AS MATERIAL,  
		COALESCE(CGLABS, Y0SLAB, 0) AS LABOR,  
		COALESCE(CGBRFS, Y0SFBR, 0) AS FIXED,  
		COALESCE(CGBRVS, Y0SVBR, 0) AS VARIABLE,  
		COALESCE(CGSTOC, Y0SOTC, 0) AS OTHER,  
		COALESCE(Y0SOC,CHSCC, 0) CURR,  
		COALESCE(Y0SSHC,CHSFC+CHSDC+CHS1C+CHS2C+CHSDWC, 0) AS SHIP_DUTY_WHSE_OTH  
        */
	FROM  
		LGDAT.STKA  
		LEFT OUTER JOIN LGDAT.ICSTM ICSTM ON  
			CGPART = V6PART AND  
			CGPLNT = V6PLNT  
		LEFT OUTER JOIN LGDAT.ICSTP ICSTP ON  
			CHPART = V6PART AND  
			CHPLNT = V6PLNT  
		LEFT OUTER JOIN LGDAT.ICSTR ICSTR ON  
			Y0PART = V6PART AND  
			Y0PLNT = V6PLNT  
        LEFT OUTER JOIN LGDAT.STKMM ON  
            AWPART = V6PART
        LEFT OUTER JOIN LGDAT.STKMP ON
            AVPART = V6PART
        LEFT OUTER JOIN LGDAT.MAJG ON
			BQGRP = COALESCE(AVMAJG , AVMAJG)
		LEFT OUTER JOIN LGDAT.MMSL MS ON
			MS.BSMJCD = COALESCE(AVMAJS, VMAJS) AND
			MS.BSMNCD = ''
		LEFT OUTER JOIN LGDAT.MMSL NS ON
			NS.BSMJCD = COALESCE(AVMAJS, AVMAJS) AND
			NS.BSMNCD = COALESCE(AVMINS, AWMINS)
		LEFT OUTER JOIN LGDAT.MMGP ON
			BRGRP = COALESCE(AVMAJG, AWMAJG) AND
			BRMGRP = COALESCE(AVMING, AWMING)
		LEFT OUTER JOIN LGDAT.CODE GE ON
			RTRIM(LTRIM(GE.A9)) = COALESCE(AVGLED, AWGLED) AND
			GE.A2 = 'GE'
		LEFT OUTER JOIN LGDAT.CODE GD ON
			RTRIM(LTRIM(GD.A9)) = COALESCE(AVGLCD, AWGLCD) AND
			GD.A2 = 'EE'
	WHERE  
		CHAR(COALESCE(CGSDAT, CHSDAT, Y0SDAT)) <> ''