SETLOCAL
SET LOGDATE=%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2%_%TIME::=-%
SET LOGDATE=%LOGDATE:.=-%
SET LOGDATE=%LOGDATE: =0%
SET APFILE=C:\users\ptrowbridge\downloads\IMPORT_R_AP_%LOGDATE%
SET ARFILE=C:\users\ptrowbridge\downloads\IMPORT_R_AR_%LOGDATE%
SET PRODFILE=C:\users\ptrowbridge\downloads\IMPORT_R_PROD_%LOGDATE%
SET INVFILE=C:\users\ptrowbridge\downloads\IMPORT_R_INV_%LOGDATE%
SET ORDFILE=C:\users\ptrowbridge\downloads\IMPORT_R_ORD_%LOGDATE%
SET REVFILE=C:\users\ptrowbridge\downloads\IMPORT_R_REV_%LOGDATE%
SET ACCFILE=C:\users\ptrowbridge\downloads\IMPORT_R_ACC_%LOGDATE%
SET SMTFILE=C:\users\ptrowbridge\downloads\IMPORT_R_SMT_%LOGDATE%
SET MTHFILE=C:\users\ptrowbridge\downloads\IMPORT_R_MTH_%LOGDATE%
SET PURFILE=C:\users\ptrowbridge\downloads\IMPORT_R_MTH_%LOGDATE%
ECHO %ARFILE%
ECHO %APFILE%
ECHO %PRODFILE%
ECHO %INVFILE%
ECHO %ORDFILE%
ECHO %REVFILE%
ECHO %ACCFILE%
ECHO %SMTFILE%
ECHO %MTHFILE%
ECHO %PURFILE%


SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_AP" -o %APFILE%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_AR" -o %ARFILE%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_PRODUCTION" -o %PRODFILE%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_INVENTORY" -o %INVFILE%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_ORDERS" -o %ORDFILE%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_REVENUE" -o %REVFILE%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_ACCT" -o %ACCFILE%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_SMAST" -o %SMTFILE%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_METH" -o %MTHFILE%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_PURCH" -o %PURFILE%