SETLOCAL
SET LOGDATE=%DATE:~10,4%-%DATE:~4,2%-%DATE:~7,2%
SET LOGFILE=C:\users\ptrowbridge\downloads\IMPORT_INCREMENTAL_%LOGDATE%_%TIME::=-%
SET LOGFILE=%LOGFILE:.=-%
SET LOGFILE=%LOGFILE: =0%
SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_INCREMENTAL" -o %LOGFILE%

REM SET LOGFILE=C:\users\ptrowbridge\downloads\IMPORT_R_PRODUCTION_%LOGDATE%_%TIME::=-%
REM SET LOGFILE=%LOGFILE:.=-%
REM SET LOGFILE=%LOGFILE: =0%
REM SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_PRODUCTION" -o %LOGFILE%

REM SET LOGFILE=C:\users\ptrowbridge\downloads\IMPORT_R_INVENTORY_%LOGDATE%_%TIME::=-%
REM SET LOGFILE=%LOGFILE:.=-%
REM SET LOGFILE=%LOGFILE: =0%
REM SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_INVENTORY" -o %LOGFILE%

REM SET LOGFILE=C:\users\ptrowbridge\downloads\IMPORT_R_ORDERS_%LOGDATE%_%TIME::=-%
REM SET LOGFILE=%LOGFILE:.=-%
REM SET LOGFILE=%LOGFILE: =0%
REM SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_ORDERS" -o %LOGFILE%

REM SET LOGFILE=C:\users\ptrowbridge\downloads\IMPORT_R_ORDERS_%LOGDATE%_%TIME::=-%
REM SET LOGFILE=%LOGFILE:.=-%
REM SET LOGFILE=%LOGFILE: =0%
REM SQLCMD -S MID-SQL02 -Q "EXEC LGDAT.IMPORT_R_PURCH" -o %LOGFILE%