SELECT
    CUSKEY1,
    CUSKEY2,
    RTRIM(CUSKEY1)+RTRIM(CUSKEY2) ILINE,
    SUBSTRING(G.ACCT,1,2) CO,
    LVL0,
    LVL1,
    LVL2,
    SUM(AMT*X.RATE) AMT,
    X.RATE
FROM 
    FANALYSISP.DBO.FFSBGLR1 G
    INNER JOIN FANALYSIS.LGDAT.MAST M ON
        M.ACCT = G.ACCT
    LEFT JOIN FANALYSIS.R.FGRP F ON
        F.BQ1GRP = M.AZGROP
    LEFT OUTER JOIN R.FFCRET X ON
        X.FCUR = AZFUT2 AND
        X.TCUR = 'US' AND
        X.PERD = G.PERD AND
        X.RTYP = 'MA'
WHERE 
    G.PERD = '1606' AND
    SUBSTRING(AZGROP,1,5) IN ('51010','41010')
GROUP BY
    CUSKEY1,
    CUSKEY2,
    RTRIM(CUSKEY1)+RTRIM(CUSKEY2),
    SUBSTRING(G.ACCT,1,2),
    LVL0,
    LVL1,
    LVL2,
    X.RATE
