--CREATE INDEX IDFISY_IDFISP ON LGDAT.VCHR(IDFISY,IDFISP)
--set showplan_text on
--set showplan_text off
SELECT
	AVTTYP, 
	IDAT, 
	DDAT, 
	AVTCO#, 
	VEND, 
	IDBNK#, 
	AVTVH#, 
	IDINV#, 
	IDVDES, 
	OP.AMT, 
	OP.PERD, 
	FHCURR, 
	MODULE, 
	BATCH, 
	TDATE, 
	PDATE, 
	COALESCE(ACCG,ACCT) ACCT, 
	D.AMT,
	PROJ,
	USRN,
	CUSKEY1, 
	CUSKEY2, 
	CUSKEY3, 
	CUSVEND,
	RECID,
	COALESCE(D.AMT,OP.AMT) AMT,
	AZGROP FGRP, 
	COALESCE(RM.DESCR,BQ1TITL) FGRP_DESCR, 
	D35DES2, 
	D35USR3
FROM
	(
		SELECT
			AVTTYP, 
			FHIDAT IDAT, 
			FHDDAT DDAT, 
			AVTCO#, 
			IDVEN#+' - '+RTRIM(BTNAME) VEND, 
			IDBNK#, 
			FORMAT(AVTVH#,'000000') AVTVH#, 
			IDINV#, 
			IDVDES, 
			AVTVAM* CASE AVTTYP WHEN 1 THEN -1 WHEN 7 THEN -1 ELSE 1 END AMT, 
			FORMAT(IDFISY,'00')+FORMAT(IDFISP,'00') AS PERD, 
			FHCURR
		FROM
			FANALYSIS.LGDAT.AVTX 
			LEFT OUTER JOIN FANALYSIS.LGDAT.VCHR ON
				IDCOM# = AVTCO# AND
				IDVCH# = AVTVH#
			LEFT OUTER JOIN FANALYSIS.LGDAT.VEND ON
				BTVEND = IDVEN#
			LEFT OUTER JOIN FANALYSIS.LGDAT."OPEN" ON
				FHCOM# = AVTCO# AND
				FHVCH# = AVTVH#
		WHERE
			AVTFIS > cast('20'+'1701' AS NUMERIC(6,0)) AND 
			(
				(
					IDFISY = 17 AND
					IDFISP <= 1
				) OR
				IDFISY < 17
			)

		UNION ALL

		SELECT
			'OPEN' AVTTYP,
			FHIDAT IDAT, 
			FHDDAT DDAT,
			FHCOM# AVTCO#,  
			FHVEN#+' - '+RTRIM(BTNAME) VEND,
			FHBANK IDBNK#,
			FHVCH# AVTVH#,
			FHINV# AS IDINV#, 
			FHVDES IDVDES,
			FHCBAL AMT,
			FORMAT(IDFISY,'00')+FORMAT(IDFISP,'00') AS PERD, 
			FHCURR
		FROM
			FANALYSIS.LGDAT."OPEN"
			LEFT OUTER JOIN FANALYSIS.LGDAT.VEND ON
				BTVEND = FHVEN#
			LEFT OUTER JOIN FANALYSIS.LGDAT.VCHR ON
				IDVCH# = FHVCH# AND
				IDCOM# = FHCOM# AND
				IDBNK# = FHBANK AND
				IDFISY = FHPYY AND
				IDFISP = FHPPER
		WHERE
			FHCBAL <> 0 AND 
			FORMAT(FHPYY,'00')+FORMAT(FHPPER,'00') >= '0901' AND
			FORMAT(FHPYY,'00')+FORMAT(FHPPER,'00') <= '1701'
	) OP
	LEFT OUTER JOIN FANALYSIS.LGDAT.CONT ON
		IFCOM# = AVTCO# AND
		IFBNK# = IDBNK#
	LEFT JOIN FANALYSISP.dbo.FFSBGLR1 D ON
		MODULE = 'APVN' AND
		D.PERD = OP.PERD AND
		CUSKEY1 = FORMAT(AVTVH#,'000000') AND
		SUBSTRING(ACCT,1,2) = CAST(AVTCO# AS VARCHAR(MAX)) AND
		ACCT <>  CAST(IFCOM# AS VARCHAR(MAX))+FORMAT(IFAPGL,'0000000000')
	LEFT OUTER JOIN 
	(
		SELECT DISTINCT
			CAST(YACOMP AS VARCHAR(MAX))+FORMAT(Y1PRVR,'0000000000') PPVG, 
			CAST(YACOMP AS VARCHAR(MAX))+CASE YAACRL WHEN 0 THEN SUBSTRING(A249,228,10) ELSE FORMAT(YAACRL,'0000000000') END ACCG
		FROM 
			LGDAT.GLIE
			LEFT OUTER JOIN FANALYSIS.LGDAT.PLNT ON
				YAPLNT = Y1PLNT
			LEFT OUTER JOIN FANALYSIS.LGDAT.NAME ON
				A7 = 'C0000'+CAST(YACOMP AS VARCHAR(MAX))
	) GS ON
		PPVG = ACCT
	LEFT OUTER JOIN FANALYSIS.LGDAT.MAST ON
		CAST(AZCOMP AS VARCHAR(MAX))+AZCODE = COALESCE(ACCG,ACCT)
	LEFT OUTER JOIN FANALYSIS.LGDAT.FGRP ON
		AZGROP = BQ1GRP
	LEFT OUTER JOIN FANALYSIS.LGDAT.GGTP ON
		D35GCDE = AZFUT3
	LEFT OUTER JOIN 
		(
			SELECT '1103040' FGRP, 'MATERIALS' DESCR UNION ALL
			SELECT '2101020' FGRP, 'MATERIALS' DESCR UNION ALL
			SELECT '5401060' FGRP, 'MATERIALS' DESCR
		) RM ON
		RM.FGRP = AZGROP
OPTION (MAXDOP 8)