WITH
	S1 (CODE, STEP, MIN_TIME, MAX_TIME, AVG_TIME) AS
	(
		SELECT 
			CAST(CODE AS VARCHAR(255)),
			CAST(STEP AS VARCHAR(255)), 
			MIN(DATEDIFF(ms, D.st, D.eT)) MIN_TIME,
			MAX(DATEDIFF(ms, D.st, D.eT)) MAX_TIME,
			AVG(DATEDIFF(ms, D.st, D.eT)) AVG_TIME
		FROM
			CTRL.IMP_DET D
			INNER JOIN CTRL.IMP_JOB J ON
				J.ID = D.ID
		WHERE
			D.ST >= '2017-03-01'
		GROUP BY 
			CODE,
			STEP
	)
SELECT
	CODE, 
	STEP,
	MIN_TIME, 
	SUM(MIN_TIME) OVER (PARTITION BY CODE) MIN_TIME_ROLL,
	MAX_TIME, 
	SUM(MAX_TIME) OVER (PARTITION BY CODE) MAX_TIME_ROLL,
	AVG_TIME, 
	SUM(AVG_TIME) OVER (PARTITION BY CODE) AVG_TIME_ROLL
FROM
	S1
