--Need to specify scalar periods in order to get an index seek on STKT
--this will be made easier by assuming that each plant is using the same fiscal periods
CREATE FUNCTION R.INVD_EFFD(@EFFD DATE)
RETURNS @X TABLE
(
	ACCT VARCHAR(12),
	COMP VARCHAR(12),
	PLNT VARCHAR(3),
	STOK VARCHAR(255),
	PART VARCHAR(20),
	PART_DESCR VARCHAR(255),
	PERD VARCHAR(4),
	QTYOH NUMERIC(20,5),
	COST NUMERIC(20,5)
) AS
BEGIN
	DECLARE @FY INT;
	DECLARE @FP INT;

	SELECT @FY = (SELECT DISTINCT N1CCYY FROM R.GLDATREF WHERE N1SD01 <= @EFFD AND N1ED01 >= @EFFD);
	SELECT @FP = (SELECT DISTINCT N1FSPP FROM R.GLDATREF WHERE N1SD01 <= @EFFD AND N1ED01 >= @EFFD);

	INSERT INTO 
		@X
	SELECT
		CAST(B.COMP AS VARCHAR(2))+CAST(Y1INVA AS VARCHAR(10)) ACCT,
		B.COMP,
		B.PLNT,
		B.STOK + ' - ' + AXLOCN STOK,
		B.PART,
		B.PART + ' - ' + COALESCE(AVDES1,AWDES1) PART_DESCR,
		B.PERD,
		B.QTYOH,
		COALESCE(FCOST, CGSTCS, CHSTCS, Y0STCS) COST
	FROM
		(
		SELECT
			COMP,
			PLNT,
			STOK,
			PART,
			PERD,
			SUM(QTYOH) QTYOH
		FROM
			(
			SELECT 
				YACOMP COMP,
				PLNT, 
				STOK, 
				PART, 
				TP PERD, 
				QTYOH
			FROM
				(
					SELECT
						YAPLNT, YACOMP, PR.*
					FROM
						LGDAT.PLNT
						INNER JOIN R.GLDATREF ON
							YACOMP = N1COMP AND
							N1SD01 <= @EFFD AND 
							N1ED01 >= @EFFD
						OUTER APPLY R.CO_TP_PP(YACOMP,N1FSYP) PR
				) X
				INNER JOIN R.STKB ON
					PLNT = YAPLNT AND 
					PERD = PP

			UNION ALL

			SELECT
				YACOMP COMP,
				BYPLNT PLNT, 
				BYSTOK STOK, 
				BYPART PART, 
				SUBSTRING(FORMAT(BYFSYY,'0000')+FORMAT(BYFSPR,'00'),3,4) PERD, 
				SUM(BYQTY*CASE BYACTN WHEN 'I' THEN -1 ELSE 1 END) QTYOH
			FROM
				LGDAT.STKT
				INNER JOIN LGDAT.PLNT ON
					YAPLNT = BYPLNT
			WHERE
				BYFSYY = @FY AND
				BYFSPR = @FP and
				BYSDAT <= @EFFD
			GROUP BY
				YACOMP,
				BYPLNT, 
				BYSTOK, 
				BYPART,
				SUBSTRING(FORMAT(BYFSYY,'0000')+FORMAT(BYFSPR,'00'),3,4)
			HAVING
				SUM(BYQTY*CASE BYACTN WHEN 'I' THEN -1 ELSE 1 END) <> 0
			) X
		GROUP BY
			COMP,
			PLNT,
			STOK,
			PART,
			PERD
		HAVING
			SUM(QTYOH) <> 0
		) B
		LEFT OUTER JOIN LGDAT.STKMM ON
			AVPART = B.PART
		LEFT OUTER JOIN LGDAT.STKMP ON 
			AWPART = B.PART
		LEFT OUTER JOIN LGDAT.GLIE ON
			Y1PLNT = B.PLNT AND
			Y1GLEC = COALESCE(AVGLED,AWGLED)
		LEFT OUTER JOIN LGDAT.ICSTM ON
			CGPART = B.PART AND
			CGPLNT = B.PLNT
		LEFT OUTER JOIN LGDAT.ICSTP ON	
			CHPART = B.PART AND
			CHPLNT = B.PLNT
		LEFT OUTER JOIN LGDAT.ICSTR ON
			Y0PART = B.PART AND
			Y0PLNT = B.PLNT
		LEFT OUTER JOIN R.FFCOSTEFFD C ON
			C.PART = B.PART AND
			C.PLNT = B.PLNT AND
			CAST(FDT AS DATETIME) + CAST(FTM AS DATETIME) <= CAST(@EFFD AS VARCHAR(10)) + ' 23:59:59' AND
			CAST(FDT AS DATETIME) + CAST(FTM AS DATETIME) >= CAST(@EFFD AS VARCHAR(10)) + ' 23:59:59'
		LEFT OUTER JOIN LGDAT.STKR ON
			AXSTKL = STOK;
	RETURN;
END

