SELECT
	B.PART,
	B.PLNT,
	B.STOK,
	'1612' PERD,
	B.QTYOH,
	COALESCE(H.FCOST, CGSTCS, CHSTCS, Y0STCS) COST_EFF
FROM
	(
	SELECT 
		BYPART PART, 
		BYPLNT PLNT, 
		BYSTOK STOK, 
		SUM(BYQTY*CASE BYACTN WHEN 'I' THEN -1 ELSE 1 END)  QTYOH
	FROM 
		LGDAT.STKT
	WHERE 
		BYFSYY = 2016 AND
		BYFSPR = 12
	GROUP BY 
		BYPART, 
		BYPLNT,
		BYSTOK 
	HAVING
		SUM(BYQTY*CASE BYACTN WHEN 'I' THEN -1 ELSE 1 END) <> 0
	) B
	LEFT OUTER JOIN R.FFCOSTEFFD H ON
		H.PART = B.PART AND
		H.PLNT = B.PLNT AND
		(
			FDT <= '2016-12-31' AND
			FTM <= '23:59:59'
		) AND
		TDT > '2016-12-31'
	LEFT OUTER JOIN LGDAT.ICSTM ON
		CGPART = B.PART AND
		CGPLNT = B.PLNT
	LEFT OUTER JOIN LGDAT.ICSTP ON
		CHPART = B.PART AND
		CHPLNT = B.PLNT
	LEFT OUTER JOIN LGDAT.ICSTR ON
		Y0PART = B.PART AND
		Y0PLNT = B.PLNT