SELECT 
	CAST(YACOMP AS VARCHAR(2))+CAST(Y1INVA AS VARCHAR(10)) ACCT, 
	 --BYPART, BYPLNT, BYSTOK, 
	PERD, 
	GRP, 
	 --COST, 
	SUM(BYQTY) BYQTY,
	SUM (LOCAL_VAL) VALUE_LOCAL 
FROM
	(
		SELECT	 
			BYPART, 
			BYPLNT, 
			BYSTOK, 
			SUBSTRING(CAST(BYFSYY AS VARCHAR(4)), 3, 2)+FORMAT(BYFSPR,'00') PERD, 
			GRP, 
			SUM (BYQTY * CASE BYACTN WHEN 'I' THEN - 1 ELSE 1 END) BYQTY ,
			SUM (BYQTY * CASE BYACTN WHEN 'I' THEN - 1 ELSE 1 END*EFFC) LOCAL_VAL
		FROM 
			LGDAT.STKT T 
			LEFT OUTER JOIN R.STGR ON 
				SRC = UPPER(RTRIM(BYSRC)+SUBSTRING(LTRIM (BYREAS+BYDREF), 1, 3))
		WHERE 
			BYFSYY = CAST('20'+SUBSTRING('1701', 1, 2) AS INT) AND 
			BYFSPR = CAST(SUBSTRING('1701', 3, 2) AS INT)
		GROUP BY 
			BYPART, 
			BYPLNT, 
			BYSTOK, 
			SUBSTRING(CAST(BYFSYY AS VARCHAR(4)), 3, 2)+FORMAT(BYFSPR,'00'), 
			GRP
		HAVING 
			SUM (BYQTY * CASE BYACTN WHEN 'I' THEN - 1 ELSE 1 END) <> 0 
	) G 
	LEFT OUTER JOIN LGDAT.STKMM ON	
		AVPART = BYPART
	LEFT OUTER JOIN LGDAT.STKMP ON			
		AWPART = BYPART
	INNER JOIN LGDAT.PLNT ON 
		YAPLNT = BYPLNT 
	LEFT OUTER JOIN LGDAT.GLIE ON 
		Y1GLEC = COALESCE(AWGLED,AVGLED) AND 
		Y1PLNT = BYPLNT 
GROUP BY 
	CAST(YACOMP AS VARCHAR(2))+CAST(Y1INVA AS VARCHAR(10)) ,
	PERD, 
	GRP

UNION ALL

SELECT 
	CAST(YACOMP AS VARCHAR(2))+CAST(Y1INVA AS VARCHAR(MAX)) ACCT, 
	FORMAT(G.N1FSYP,'0000') FSPR, 
	'COST ROLL' GRP, 
	SUM (TQTY) QTY,
	ROUND (SUM ((TCOST - FCOST) * TQTY), 2) VALUE_LOCAL 
FROM 
	R.GLDATREF G 
	INNER JOIN R.PRFSPR P ON 
		P.N1COMP = G.N1COMP AND 
		P.CURRP = FORMAT(G.N1FSYP,'0000')
	INNER JOIN LGDAT.PLNT ON 
		YACOMP = G.N1COMP 
	INNER JOIN R.FFCOSTEFFD C ON 
		C.PLNT = YAPLNT AND 
		C.TDT >= N1SD01 AND 
		C.TDT <= N1ED01 
	LEFT OUTER JOIN LGDAT.STKMM ON
		AVPART = C.PART 
	LEFT OUTER JOIN LGDAT.STKMP ON
		AWPART = C.PART 
	LEFT JOIN LGDAT.GLIE ON 
		Y1PLNT = C.PLNT AND 
		Y1GLEC = COALESCE(AVGLED,AWGLED)
WHERE 
	FORMAT(G.N1FSYP,'0000') = '1612' AND 
	TCOST - FCOST <> 0 AND 
	TQTY <> 0 
GROUP BY 
	CAST(YACOMP AS VARCHAR(2))+CAST(Y1INVA AS VARCHAR(MAX)), FORMAT(G.N1FSYP,'0000')
	
	
  
UNION ALL 
  
SELECT 
	YACOMP+Y1INVA ACCT, 
	CURRP, 
	'OPEN' COMPONENT, 
	ROUND (SUM (QTYOH * COST_EFF), 2) VALUE_LOCAL	 
FROM 
	RLARP.FFSTKBP 
	INNER JOIN LGDAT.PLNT ON 
		YAPLNT = PLNT 
	INNER JOIN RLARP.VW_PRFSPR ON 
		COMP = YACOMP AND 
		PRIORP = PERD 
	LEFT OUTER JOIN RLARP.VW_FFSTKMX ON 
		AVPART = PART 
	LEFT OUTER JOIN LGDAT.GLIE ON 
		Y1PLNT = PLNT AND 
		Y1GLEC = AVGLED 
WHERE 
	CURRP = VPERD 
GROUP BY 
	YACOMP+Y1INVA, CURRP 
  
UNION ALL 
  
SELECT 
	YACOMP+Y1INVA ACCT, 
	PERD, 
	'END' COMPONENT, 
	ROUND (SUM (QTYOH * COST_EFF), 2) VALUE_LOCAL	 
FROM 
	RLARP.FFSTKBP 
	INNER JOIN LGDAT.PLNT ON 
		YAPLNT = PLNT 
	LEFT OUTER JOIN RLARP.VW_FFSTKMX ON 
		AVPART = PART 
	LEFT OUTER JOIN LGDAT.GLIE ON 
		Y1PLNT = PLNT AND 
		Y1GLEC = AVGLED 
WHERE 
	PERD = VPERD 
GROUP BY 
	YACOMP+Y1INVA, PERD  ; 