--SET SHOWPLAN_TEXT OFF;
SET STATISTICS IO ON;
SELECT
    ADEP,
    ARSC,
    SUBSTRING(PART,1,8) MOLD,
    COALESCE(AVMAJG, AWMAJG) MAJG,
    NWPLNT,
    NWFSYY,
    NWFSPP,
    SUM(CASE ACTN WHEN 'CPG' THEN PQTY ELSE 0 END) CPG,
    SUM(CASE ACTN WHEN 'CPS' THEN PQTY ELSE 0 END) CPS
FROM 
    FANALYSISP.DBO.FFPDGLR1
    INNER JOIN FANALYSIS.LGDAT.RPRH ON  
        NWBTID = BTID
    LEFT OUTER JOIN FANALYSIS.LGDAT.STKMM ON
        AVPART = PART
    LEFT OUTER JOIN FANALYSIS.LGDAT.STKMP ON
        AWPART = PART
WHERE   
    /*
    (
        (
            NWFSYY = 16 AND
            NWFSPP >= 3
        ) OR
        (
                NWFSYY =17 AND 
                NWFSPP < 3
        ) 
    )
    */
    NWFSYY >= 16
    AND
    ACTN IN ('CPG','CPS')
GROUP BY
    ADEP,
    ARSC,
    SUBSTRING(PART,1,8),
    COALESCE(AVMAJG, AWMAJG),
    NWPLNT,
    NWFSYY,
    NWFSPP