SELECT
    NWPLNT,
    NWFSYY, 
    NWFSPP, 
    OADEPT, 
    OARESC, 
    SUBSTRING(OAPART,1,8) MOLD,
    SUM(OAQTYG) OAQTYG, 
    SUM(OAQTYS) OAQTYS
FROM
    LGDAT.RPRH
    INNER JOIN LGDAT.RPRR ON    
        OABTID = NWBTID
    LEFT OUTER JOIN LGDAT.STKMM ON
        AVPART = OAPART
    LEFT OUTER JOIN LGDAT.STKMP ON  
        AWPART = OAPART
WHERE
    NWFSYY >= 16
GROUP BY   
    NWPLNT,
    NWFSYY, 
    NWFSPP, 
    OADEPT, 
    OARESC,
    SUBSTRING(OAPART,1,8)