SELECT  
	FORMAT(DHARYR,'00')+FORMAT(DHARPR,'00') FSPR,  
	DHCOMP INV_COMP,  
	DHPLNT INV_PLNT,  
	DHCURR INV_CURR,  
	CURR COMP_CURR,  
	BC.BVCOMP BILL_REMIT_TO,  
	BC.BVCLAS BILL_CUST_CLASS,  
	BC.BVCUST+' - '+RTRIM(BC.BVNAME) BILL_CUST,  
	COALESCE(CG.CGRP,BC.BVCUST+' - '+RTRIM(BC.BVNAME)) ACCOUNT,
	BC.BVCITY, 
	BC.BVPRCD BILL_PROV,  
	BC.BVCTRY BILL_CTRY,  
	SC.BVCOMP SHIP_REMIT_TO,  
	SC.BVCLAS SHIP_CUST_CLASS,  
	SC.BVCUST+' - '+RTRIM(SC.BVNAME) SHIP_CUST,  
	SC.BVCITY, 
	SC.BVPRCD SHIP_PROV,  
	SC.BVCTRY SHIP_CTRY,  
	DIGLCD+' - '+RTRIM(G.A30) GLCODE,  
	COALESCE(AVGLED, AWGLED) GLEC,
	DIREAS+' - '+RTRIM(R.A30) REAS,  
	RTRIM(DCPROM) PROMOTION,  
	DHINCR INV_TYPE,   
	ZWSAL# CMSGL,  
	AZGROP+' - '+RTRIM(BQ1TITL) FGRP,  
	SUM(DIQTSH*CASE DHINCR WHEN 'C' THEN -1 ELSE 1 END) QTY_SHIP,  
	ROUND(SUM(DICTEX*CASE DHINCR WHEN 'C' THEN -1 ELSE 1 END),2) COST,  
	ROUND(SUM(DIEXT*CASE DHINCR WHEN 'C' THEN -1 ELSE 1 END),2) INVOICE,  
	ROUND(SUM(DICTEX*CASE DHINCR WHEN 'C' THEN -1 ELSE 1 END*CX.RATE),2) COST_USD,  
	ROUND(SUM(DIEXT*CASE DHINCR WHEN 'C' THEN -1 ELSE 1 END*IX.RATE),2) INVOICE_USD  
FROM  
	LGDAT.OIH  
	INNER JOIN LGDAT.OID ON  
		DIINV# = DHINV#  
	LEFT OUTER JOIN LGDAT.OCRH ON  
		DCORD# = DHORD#  
	LEFT OUTER JOIN LGDAT.CODE G ON  
		G.A2 = 'EE' AND  
		LTRIM(RTRIM(G.A9)) = DIGLCD  
	LEFT OUTER JOIN LGDAT.CODE R ON  
		R.A2 = 'RS' AND  
		LTRIM(RTRIM(R.A9)) = DIREAS  
	LEFT OUTER JOIN LGDAT.CUST BC ON  
		BC.BVCUST = DHBCS#  
	LEFT OUTER JOIN LGDAT.CUST SC ON  
		SC.BVCUST = DHSCS#   
	LEFT OUTER JOIN R.FFCUST CG ON
		CG.CUSTN = DHBCS#
	LEFT OUTER JOIN LGDAT.PLNT ON  
		YAPLNT = DHPLNT  
	LEFT OUTER JOIN LGDAT.STKMM ON
		AVPART = DIPART
	LEFT OUTER JOIN LGDAT.STKMP ON
		AWPART = DIPART
	LEFT OUTER JOIN LGDAT.GLIE ON  
		Y1PLNT = DHPLNT AND  
		Y1GLEC = COALESCE(AVGLED, AWGLED)
	LEFT OUTER JOIN LGDAT.ARMASC ON  
		ZWCOMP = BC.BVCOMP AND  
		ZWKEY1 = BC.BVARCD AND  
		ZWKEY2 = DIGLCD  
	LEFT OUTER JOIN R.FFCRET IX ON  
		IX.PERD = FORMAT(DHARYR,'00')+FORMAT(DHARPR,'00') AND  
		IX.FCUR = DHCURR AND  
		IX.TCUR = 'US' AND  
		IX.RTYP = 'ME'  
	LEFT OUTER JOIN R.COPR CP ON  
		CP.COMP = DHCOMP  
	LEFT OUTER JOIN R.FFCRET CX ON  
		CX.PERD = FORMAT(DHARYR,'00')+FORMAT(DHARPR,'00') AND  
		CX.FCUR = CURR AND  
		CX.TCUR = 'US' AND  
		CX.RTYP = 'ME'  
	LEFT OUTER JOIN LGDAT.MAST ON  
		CAST(AZCOMP AS VARCHAR(10))+AZCODE = CAST(ZWSAL#  AS VARCHAR(12))
	LEFT OUTER JOIN LGDAT.FGRP ON  
		BQ1GRP = AZGROP  
	LEFT OUTER JOIN R.GLDATREF GP ON  
		N1COMP = DHCOMP AND  
		N1FSYP = FORMAT(DHARYR,'00')+FORMAT(DHARPR,'00')
WHERE
	FORMAT(DHARYR,'00')+FORMAT(DHARPR,'00') >= '1407' AND
	FORMAT(DHARYR,'00')+FORMAT(DHARPR,'00') <= '1605'
GROUP BY  
	FORMAT(DHARYR,'00')+FORMAT(DHARPR,'00'), 	  
	DHCOMP ,  
	DHPLNT ,  
	DHCURR ,  
	CURR,  
	BC.BVCOMP ,  
	BC.BVCLAS ,  
	BC.BVCUST+' - '+RTRIM(BC.BVNAME) ,  
	COALESCE(CG.CGRP,BC.BVCUST+' - '+RTRIM(BC.BVNAME)),
	BC.BVCITY, 
	BC.BVPRCD ,  
	BC.BVCTRY ,  
	SC.BVCOMP ,  
	SC.BVCLAS ,  
	SC.BVCUST+' - '+RTRIM(SC.BVNAME) ,  
	SC.BVCITY, 
	SC.BVPRCD ,  
	SC.BVCTRY ,  
	DIGLCD+' - '+RTRIM(G.A30) ,  
	COALESCE(AVGLED, AWGLED),  
	DIREAS+' - '+RTRIM(R.A30) ,  
	RTRIM(DCPROM) ,  
	DHINCR,  
	ZWSAL#,  
	AZGROP+' - '+RTRIM(BQ1TITL)
OPTION (MAXDOP 8, RECOMPILE)