WITH C AS (
	SELECT
		CUSVEND VEND, 
		'00000' + CUSKEY3 MRKEY, 
		MIN(TDATE) TDATE
	FROM 
		FANALYSISP.DBO.FFSBGLR1 
	WHERE 
		MODULE IN ('APAC') AND 
		PERD >= '1601'
	GROUP BY
		CUSVEND,
		CUSKEY3
	)

	SELECT
		C.VEND, 
		C.MRKEY, 
		CAST(C.TDATE AS DATE) ACCR_DATE, 
		CAST(G.TDATE AS DATE) AS VCHR_DATE,
		DATEDIFF(DAY,CAST(C.TDATE AS DATE),CAST(G.TDATE AS DATE)) DIFF
	FROM
		FANALYSISP.DBO.FFSBGLR1 G
		INNER JOIN C ON
			C.MRKEY = CUSKEY3
	WHERE
		MODULE = 'APVN' AND
		CUSKEY3D = 'RKEY'

OPTION (MAXDOP 8)