SELECT 
	IDCOM#,
	IDVEN#, 
	MIN(IDDATE) MIND,
	MAX(IDDATE) MAXD,
	DATEDIFF(DAY,MIN(IDDATE),MAX(IDDATE)) DATE_RANGE,
	COUNT(*) NUM_VOUCHERS,
	ROUND(CAST(DATEDIFF(DAY,MIN(IDDATE),MAX(IDDATE)) AS FLOAT)/CAST(COUNT(*) AS FLOAT),0) FREQ_DAYS
FROM 
	LGDAT.VCHR
WHERE
	IDFISY >= 16 AND IDFISY < 18
GROUP BY
	IDCOM#,
	IDVEN#
HAVING
	DATEDIFF(DAY,MIN(IDDATE),MAX(IDDATE)) > 0