SELECT
	AVTCHQ,
	SUM(AVTAMT) AVTAMT,
	AVTTDT,
	FHVEN# + ' - ' + BTNAME VEND,
	FHBANK
FROM 
	LGDAT.AVTX X
	INNER JOIN LGDAT."OPEN" O ON
		O.FHCOM# = X.AVTCO# AND
		O.FHVCH# = X.AVTVH#
    LEFT OUTER JOIN LGDAT.VEND ON   
        BTVEND = FHVEN#
WHERE 
    FHCOM# <> 66 AND
    FHBANK = 'U' AND
    BTNAME NOT LIKE '%(WIRE%' AND
    BTNAME NOT LIKE '%(wire%' AND
    BTNAME NOT LIKE '% wire' AND
    BTNAME NOT LIKE '% WIRE' AND
	AVTCHQ <> 0 AND 
	AVTTDT >= '2016-01-01' AND 
	AVTTYP IN (' 4',' 5')
GROUP BY
	AVTCHQ,
	AVTTDT,
	FHVEN# + ' - ' + BTNAME,
	FHBANK