WITH I AS (
	SELECT
		AVTCO# COM,
		AVTVH# VCH,
		FHVEN# VEN,
		O.FHGRS GRS,
		MIN(AVTTDT) MIND,
		MAX(AVTTDT) MAXD,
		DATEDIFF(DAY, MIN(AVTTDT), MAX(AVTTDT)) HOLDDAYS
	FROM 
		LGDAT.AVTX	X
		INNER JOIN LGDAT."OPEN" O ON
			AVTCO# = FHCOM# AND
			AVTVH# = FHVCH#
	WHERE 
		FHPYY >= 16 AND FHCBAL = 0
	GROUP BY
		AVTCO#,
		AVTVH#,
		FHVEN#,
		FHGRS
	)
SELECT
	COM, 
	VEN, 
	SUM(GRS),
	COUNT(*) CNT,
	AVG(HOLDDAYS) AVGHOLD,
	SUM(GRS*HOLDDAYS)/SUM(GRS) WA_HOLDDAYS
FROM
	I
GROUP BY
	COM,
	VEN
HAVING
	SUM(GRS) <> 0