WITH 
S AS (
SELECT
    VERSION,
	PLNT,
	PART,
	STATEMENT_LINE,
	R_CURRENCY,
	C_CURRENCY,
	MAJG,
	MING,
	MAJS,
	MINS,
	SUM(VALUE_LOCAL*CASE R_CURRENCY WHEN 'CA' THEN .75 ELSE 1 END) REVENUE_USD,
	SUM(QTY) QTY
FROM
	QGPL.FFBS0516
WHERE
	B_SHIPDATE + I_SHIPDATE DAYS >= '2017-06-01' AND
	B_SHIPDATE + I_SHIPDATE DAYS < '2018-06-01'
GROUP BY
    VERSION,
	PLNT,
	PART,
	STATEMENT_LINE,
	R_CURRENCY,
	C_CURRENCY,
	MAJG,
	MING,
	MAJS,
	MINS
)
,AGG AS (
SELECT
    S.VERSION,
	S.PART,
	S.PLNT,
	S.STATEMENT_LINE,
	S.R_CURRENCY,
	S.C_CURRENCY,
	S.MAJG,
	S.MING,
	S.MAJS,
	S.MINS,
    S.REVENUE_USD REVENUE_USD,
    S.QTY,
	SUM(ERQTYS*QTY) QTYS,
	SUM(ERQTY*QTY) QTYG,
	SUM(
		(ERQTY+ERQTYS)*(1/RUNTIME)*QTY
	) EH,
    SUM(COALESCE(BASEX,0)*QTY) BASE,
    SUM(COALESCE(FRTX,0)*QTY) FREIGHT,
    SUM(COALESCE(DUTYX,0)*QTY) DUTY,
    SUM(COALESCE(MULT1X,0)*QTY) MULT1,
    SUM(COALESCE(MULT2X,0)*QTY) MULT2,
    SUM(COALESCE(SHIPHX,0)*QTY) SHIPH,
    SUM(COALESCE(OSFTX,0)*QTY) SUBFRTOUT,
    SUM(COALESCE(OSFFX,0)*QTY) SUBFRTIN,
    SUM(COALESCE(CURRX,0)*QTY) CURRENCY,
    SUM(COALESCE(SUBCX,0)*QTY) SUBCONTR,
    SUM(LABRX*QTY) LABRUN,
    SUM(VARRX*QTY) VARRUN,
    SUM(FIXRX*QTY) FIXRUN,
    SUM(LABSX*QTY) LABSET,
    SUM(VARSX*QTY) VARSET,
    SUM(FIXSX*QTY) FIXSET,
    SUM(
        COALESCE(BASEXS,0)*QTY +
        COALESCE(FRTXS,0)*QTY +
        COALESCE(DUTYXS,0)*QTY +
        COALESCE(MULT1XS,0)*QTY +
        COALESCE(MULT2XS,0)*QTY +
        COALESCE(SHIPHXS,0)*QTY +
        COALESCE(OSFTXS,0)*QTY+
        COALESCE(OSFFXS,0)*QTY +
        COALESCE(CURRXS,0)*QTY +
        COALESCE(SUBCXS,0)*QTY +
        COALESCE(LABRXS,0)*QTY+
        COALESCE(VARRXS,0)*QTY+
        COALESCE(FIXRXS,0)*QTY+
        COALESCE(LABSXS,0)*QTY+
        COALESCE(VARSXS,0)*QTY+
        COALESCE(FIXSXS,0)*QTY
    ) SCRAP,
    ROUND(
        SUM(
                ---good----
                COALESCE(BASEX,0)*QTY +
                COALESCE(FRTX,0)*QTY +
                COALESCE(DUTYX,0)*QTY +
                COALESCE(MULT1X,0)*QTY +
                COALESCE(MULT2X,0)*QTY +
                COALESCE(SHIPHX,0)*QTY +
                COALESCE(OSFTX,0)*QTY +
                COALESCE(OSFFX,0)*QTY +
                COALESCE(CURRX,0)*QTY +
                COALESCE(SUBCX,0)*QTY +
                COALESCE(LABRX,0)*QTY+
                COALESCE(VARRX,0)*QTY+
                COALESCE(FIXRX,0)*QTY+
                COALESCE(LABSX,0)*QTY+
                COALESCE(VARSX,0)*QTY+
                COALESCE(FIXSX,0)*QTY+
                ---scrap----
                COALESCE(BASEXS,0)*QTY +
                COALESCE(FRTXS,0)*QTY +
                COALESCE(DUTYXS,0)*QTY +
                COALESCE(MULT1XS,0)*QTY +
                COALESCE(MULT2XS,0)*QTY +
                COALESCE(SHIPHXS,0)*QTY +
                COALESCE(OSFTXS,0)*QTY +
                COALESCE(OSFFXS,0)*QTY +
                COALESCE(CURRXS,0)*QTY +
                COALESCE(SUBCXS,0)*QTY +
                COALESCE(LABRXS,0)*QTY+
                COALESCE(VARRXS,0)*QTY+
                COALESCE(FIXRXS,0)*QTY+
                COALESCE(LABSXS,0)*QTY+
                COALESCE(VARSXS,0)*QTY+
                COALESCE(FIXSXS,0)*QTY
        )
    ,5) TOTAL_CALC
FROM
	S
    INNER JOIN QGPL.FFBSREQF C ON
		S.PART = C.MAST AND
		S.PLNT = C.MPLT
GROUP BY
    S.VERSION,
	S.PART,
	S.PLNT,
	S.STATEMENT_LINE,
	S.R_CURRENCY,
	S.C_CURRENCY,
	S.MAJG,
	S.MING,
	S.MAJS,
	S.MINS,
    S.REVENUE_USD,
    S.QTY
)

SELECT
    AGG.*,
    COALESCE(CNSTCS,COSTCS,Y3STCS)*AGG.QTY FUT_STDCOST,
    COALESCE(AVNWHT,AWNWHT)*CASE COALESCE(AVNWUN,AWNWUN) WHEN 'KG' THEN 2.2046 ELSE 1 END*AGG.QTY WGHT,
    SEQ,
    ACTION
FROM
    AGG
    LEFT OUTER JOIN LGDAT.FTCSTM ON
        CNPART = PART AND
        CNPLNT = PLNT
    LEFT OUTER JOIN LGDAT.FTCSTP ON
        COPART = PART AND
        COPLNT = PLNT
    LEFT OUTER JOIN LGDAT.FTCSTR ON
        Y3PART = PART AND
        Y3PLNT = PLNT
    LEFT OUTER JOIN QGPL.FFVERS ON
        VERS = VERSION
    LEFT OUTER JOIN LGDAT.STKMM ON
        AVPART = PART
    LEFT OUTER JOIN LGDAT.STKMP ON
        AWPART = PART