WITH 
S AS (
SELECT
	VERSION,
	CHAN,
	GEO,
	GLEC,
	PLNT,
	PART,
	STATEMENT_LINE,
	R_CURRENCY,
	C_CURRENCY,
	MAJG,
	MING,
	MAJS,
	MINS,
	SUM(VALUE_LOCAL*CASE R_CURRENCY WHEN 'CA' THEN .75 ELSE 1 END) REVENUE_USD,
	SUM(QTY) QTY
FROM
	QGPL.FFBS0516
WHERE
	B_SHIPDATE + I_SHIPDATE DAYS >= '2017-06-01' AND
	B_SHIPDATE + I_SHIPDATE DAYS < '2018-06-01'
GROUP BY
	VERSION,
	CHAN,
	GEO,
	GLEC,
	PLNT,
	PART,
	STATEMENT_LINE,
	R_CURRENCY,
	C_CURRENCY,
	MAJG,
	MING,
	MAJS,
	MINS
)

SELECT
	'PLAN' SRCE,
	S.VERSION,
	V.ACTION,
	V.SEQ,
	S.CHAN,
	S.GEO,
	S.GLEC,
	S.PLNT,
	S.STATEMENT_LINE,
	S.R_CURRENCY,
	S.C_CURRENCY,
	S.MAJG,
	S.MING,
	S.MAJS,
	S.MINS,
	C.GLED GLED_PS,
	C.MAJG MAJG_PS,
	C.MING MING_PS,
	C.DEP DEP_PS,
	C.REPL REPL_PS,
	C.RTYP RTYP_PS,
	C.SPLNT||'-'||C.CPLNT PLTS_PS,
	SUM(ERQTYS*QTY) QTYS,
	SUM(ERQTY*QTY) QTYG,
	SUM((ERQTY)*(1/RUNTIME)*QTY) EH,
	SUM((ERQTYS)*(1/RUNTIME)*QTY) EH_SCRAP,
    SUM(COALESCE(BASEX,0)*QTY) BASE,
	SUM(COALESCE(BASEXS,0)*QTY) BASE_SCRAP,
    SUM(COALESCE(FRTX,0)*QTY) FREIGHT,
	SUM(COALESCE(FRTXS,0)*QTY) FREIGHT_SCRAP,
    SUM(COALESCE(DUTYX,0)*QTY) DUTY,
	SUM(COALESCE(DUTYXS,0)*QTY) DUTY_SCRAP,
    SUM(COALESCE(MULT1X,0)*QTY) MULT1,
	SUM(COALESCE(MULT1XS,0)*QTY) MULT1_SCRAP,
    SUM(COALESCE(MULT2X,0)*QTY) MULT2,
	SUM(COALESCE(MULT2XS,0)*QTY) MULT2_SCRAP,
    SUM(COALESCE(SHIPHX,0)*QTY) SHIPH,
	SUM(COALESCE(SHIPHXS,0)*QTY) SHIPH_SCRAP,
    SUM(COALESCE(OSFTX,0)*QTY) SUBFRTOUT,
	SUM(COALESCE(OSFTXS,0)*QTY) SUBFRTOUT_SCRAP,
    SUM(COALESCE(OSFFX,0)*QTY) SUBFRTIN,
	SUM(COALESCE(OSFFXS,0)*QTY) SUBFRTIN_SCRAP,
    SUM(COALESCE(CURRX,0)*QTY) CURRENCY,
	SUM(COALESCE(CURRXS,0)*QTY) CURRENCY_SCRAP,
    SUM(COALESCE(SUBCX,0)*QTY) SUBCONTR,
	SUM(COALESCE(SUBCXS,0)*QTY) SUBCONTR_SCRAP,
    SUM(LABRX*QTY+LABSX*QTY) LAB,
	SUM(COALESCE(LABRXS,0)*QTY+COALESCE(LABSXS,0)*QTY) LAB_SCRAP,
    SUM(VARRX*QTY+VARSX*QTY) VAR,
	SUM(COALESCE(VARRXS,0)*QTY+COALESCE(VARSXS,0)*QTY) VAR_SCRAP,
    SUM(FIXRX*QTY+FIXSX*QTY) FIX,
	SUM(COALESCE(FIXRXS,0)*QTY+COALESCE(FIXSXS,0)*QTY) FIX_SCRAP,
    ROUND(
        SUM(
                ---good----
                COALESCE(BASEX,0)*QTY +
                COALESCE(FRTX,0)*QTY +
                COALESCE(DUTYX,0)*QTY +
                COALESCE(MULT1X,0)*QTY +
                COALESCE(MULT2X,0)*QTY +
                COALESCE(SHIPHX,0)*QTY +
                COALESCE(OSFTX,0)*QTY +
                COALESCE(OSFFX,0)*QTY +
                COALESCE(CURRX,0)*QTY +
                COALESCE(SUBCX,0)*QTY +
                COALESCE(LABRX,0)*QTY+
                COALESCE(VARRX,0)*QTY+
                COALESCE(FIXRX,0)*QTY+
                COALESCE(LABSX,0)*QTY+
                COALESCE(VARSX,0)*QTY+
                COALESCE(FIXSX,0)*QTY+
                ---scrap----
                COALESCE(BASEXS,0)*QTY +
                COALESCE(FRTXS,0)*QTY +
                COALESCE(DUTYXS,0)*QTY +
                COALESCE(MULT1XS,0)*QTY +
                COALESCE(MULT2XS,0)*QTY +
                COALESCE(SHIPHXS,0)*QTY +
                COALESCE(OSFTXS,0)*QTY +
                COALESCE(OSFFXS,0)*QTY +
                COALESCE(CURRXS,0)*QTY +
                COALESCE(SUBCXS,0)*QTY +
                COALESCE(LABRXS,0)*QTY+
                COALESCE(VARRXS,0)*QTY+
                COALESCE(FIXRXS,0)*QTY+
                COALESCE(LABSXS,0)*QTY+
                COALESCE(VARSXS,0)*QTY+
                COALESCE(FIXSXS,0)*QTY
        )
    ,5) TOTAL_CALC,
	SUM(COALESCE(AVNWHT,AWNWHT)*CASE COALESCE(AVNWUN,AWNWUN) WHEN 'KG' THEN 2.2046 ELSE 1 END*ERQTY*QTY) WGHT,
	SUM(COALESCE(AVNWHT,AWNWHT)*CASE COALESCE(AVNWUN,AWNWUN) WHEN 'KG' THEN 2.2046 ELSE 1 END*ERQTYS*QTY) WGHT_SCRAP
FROM
	S
    INNER JOIN QGPL.FFBSREQF C ON
		S.PART = C.MAST AND
		S.PLNT = C.MPLT
	LEFT OUTER JOIN QGPL.FFVERS V ON
		VERS = VERSION
	LEFT OUTER JOIN LGDAT.STKMM ON
		AVPART = C.PART
	LEFT OUTER JOIN LGDAT.STKMP ON
		AWPART = C.PART
GROUP BY
	S.VERSION,
	V.ACTION,
	V.SEQ,
	S.CHAN,
	S.GEO,
	S.GLEC,
	S.PLNT,
	S.STATEMENT_LINE,
	S.R_CURRENCY,
	S.C_CURRENCY,
	S.MAJG,
	S.MING,
	S.MAJS,
	S.MINS,
	C.GLED,
	C.MAJG,
	C.MING,
	C.DEP,
	C.REPL,
	C.RTYP,
	C.SPLNT||'-'||C.CPLNT

UNION ALL

SELECT
	'CURR' SRCE,
	S.VERSION,
	V.ACTION,
	V.SEQ,
	S.CHAN,
	S.GEO,
	S.GLEC,
	S.PLNT,
	S.STATEMENT_LINE,
	S.R_CURRENCY,
	S.C_CURRENCY,
	S.MAJG,
	S.MING,
	S.MAJS,
	S.MINS,
	C.GLED GLED_PS,
	C.MAJG MAJG_PS,
	C.MING MING_PS,
	C.DEP DEP_PS,
	C.REPL REPL_PS,
	C.RTYP RTYP_PS,
	C.SPLNT||'-'||C.CPLNT PLTS_PS,
	SUM(ERQTYS*QTY) QTYS,
	SUM(ERQTY*QTY) QTYG,
	SUM((ERQTY)*(1/RUNTIME)*QTY) EH,
	SUM((ERQTYS)*(1/RUNTIME)*QTY) EH_SCRAP,
    SUM(COALESCE(BASEX,0)*QTY) BASE,
	SUM(COALESCE(BASEXS,0)*QTY) BASE_SCRAP,
    SUM(COALESCE(FRTX,0)*QTY) FREIGHT,
	SUM(COALESCE(FRTXS,0)*QTY) FREIGHT_SCRAP,
    SUM(COALESCE(DUTYX,0)*QTY) DUTY,
	SUM(COALESCE(DUTYXS,0)*QTY) DUTY_SCRAP,
    SUM(COALESCE(MULT1X,0)*QTY) MULT1,
	SUM(COALESCE(MULT1XS,0)*QTY) MULT1_SCRAP,
    SUM(COALESCE(MULT2X,0)*QTY) MULT2,
	SUM(COALESCE(MULT2XS,0)*QTY) MULT2_SCRAP,
    SUM(COALESCE(SHIPHX,0)*QTY) SHIPH,
	SUM(COALESCE(SHIPHXS,0)*QTY) SHIPH_SCRAP,
    SUM(COALESCE(OSFTX,0)*QTY) SUBFRTOUT,
	SUM(COALESCE(OSFTXS,0)*QTY) SUBFRTOUT_SCRAP,
    SUM(COALESCE(OSFFX,0)*QTY) SUBFRTIN,
	SUM(COALESCE(OSFFXS,0)*QTY) SUBFRTIN_SCRAP,
    SUM(COALESCE(CURRX,0)*QTY) CURRENCY,
	SUM(COALESCE(CURRXS,0)*QTY) CURRENCY_SCRAP,
    SUM(COALESCE(SUBCX,0)*QTY) SUBCONTR,
	SUM(COALESCE(SUBCXS,0)*QTY) SUBCONTR_SCRAP,
    SUM(LABRX*QTY+LABSX*QTY) LAB,
	SUM(COALESCE(LABRXS,0)*QTY+COALESCE(LABSXS,0)*QTY) LAB_SCRAP,
    SUM(VARRX*QTY+VARSX*QTY) VAR,
	SUM(COALESCE(VARRXS,0)*QTY+COALESCE(VARSXS,0)*QTY) VAR_SCRAP,
    SUM(FIXRX*QTY+FIXSX*QTY) FIX,
	SUM(COALESCE(FIXRXS,0)*QTY+COALESCE(FIXSXS,0)*QTY) FIX_SCRAP,
    ROUND(
        SUM(
                ---good----
                COALESCE(BASEX,0)*QTY +
                COALESCE(FRTX,0)*QTY +
                COALESCE(DUTYX,0)*QTY +
                COALESCE(MULT1X,0)*QTY +
                COALESCE(MULT2X,0)*QTY +
                COALESCE(SHIPHX,0)*QTY +
                COALESCE(OSFTX,0)*QTY +
                COALESCE(OSFFX,0)*QTY +
                COALESCE(CURRX,0)*QTY +
                COALESCE(SUBCX,0)*QTY +
                COALESCE(LABRX,0)*QTY+
                COALESCE(VARRX,0)*QTY+
                COALESCE(FIXRX,0)*QTY+
                COALESCE(LABSX,0)*QTY+
                COALESCE(VARSX,0)*QTY+
                COALESCE(FIXSX,0)*QTY+
                ---scrap----
                COALESCE(BASEXS,0)*QTY +
                COALESCE(FRTXS,0)*QTY +
                COALESCE(DUTYXS,0)*QTY +
                COALESCE(MULT1XS,0)*QTY +
                COALESCE(MULT2XS,0)*QTY +
                COALESCE(SHIPHXS,0)*QTY +
                COALESCE(OSFTXS,0)*QTY +
                COALESCE(OSFFXS,0)*QTY +
                COALESCE(CURRXS,0)*QTY +
                COALESCE(SUBCXS,0)*QTY +
                COALESCE(LABRXS,0)*QTY+
                COALESCE(VARRXS,0)*QTY+
                COALESCE(FIXRXS,0)*QTY+
                COALESCE(LABSXS,0)*QTY+
                COALESCE(VARSXS,0)*QTY+
                COALESCE(FIXSXS,0)*QTY
        )
    ,5) TOTAL_CALC
FROM
	S
    INNER JOIN QGPL.FFBSREQC C ON
		S.PART = C.MAST AND
		S.PLNT = C.MPLT
	LEFT OUTER JOIN QGPL.FFVERS V ON
		VERS = VERSION
GROUP BY
	S.VERSION,
	V.ACTION,
	V.SEQ,
	S.CHAN,
	S.GEO,
	S.GLEC,
	S.PLNT,
	S.STATEMENT_LINE,
	S.R_CURRENCY,
	S.C_CURRENCY,
	S.MAJG,
	S.MING,
	S.MAJS,
	S.MINS,
	C.GLED,
	C.MAJG,
	C.MING,
	C.DEP,
	C.REPL,
	C.RTYP,
	C.SPLNT||'-'||C.CPLNT

