SELECT
	COALESCE(RM.DESCR,BQ1TITL) FGRP_DESCR,
	D35USR3 FUNC_AREA,
	IGVEN#||' - '||RTRIM(BTNAME) VENDOR,
	IDDATE INVOICE_DATE,
	FHDDAT DUE_DATE,
	CAST(PDATE AS DATE) VCHR_DATE,
	IGCDAT CHECK_DATE,
	CAST(NULL AS DATE) PAY_DATE,
	IGCHQ# CHECK_NUM,
	COALESCE(AMT,IGGROS) AMOUNT,
	'OPEN CHECKS' SRCE
	/*
	DIGITS(IGFSYY) IGFSYY,
	DIGITS(IGFSPP) IGFSPP,
	DIGITS(IGFSYY)||DIGITS(IGFSPP) IGPERD,
	IGCOM#,
	BTBANK,
	DIGITS(AVTVH#) AVTVH#,
	IDINV#,
	IGCHQ#,
	ETHTOT,
	IGVEN#,
	BTNAME,
	IGGROS,
	IFCOM#||DIGITS(IFAPGL),
	COALESCE(ACCG,ACCT) ACCT,
	PROJ,
	AZGROP,
	AMT,
	IESTS
	*/
FROM
	LGDAT.CHQR
	INNER JOIN LGDAT.UCHQ ON
		IECHQ# = IGCHQ# AND
		IECOM# = IGCOM# AND
		IEBNK# = IGBNK#
	LEFT OUTER JOIN LGDAT.EFTBD ON
		ETDEFT# = IGCHQ# AND
		ETDCOMN = IGCOM# AND
		ETDVEND = IGVEN#
	LEFT OUTER JOIN LGDAT.EFTBH ON
		ETHCOMN = ETDCOMN AND 
		ETHEBNK = ETDEBNK AND 
		ETHBTC# = ETDBTC#
	LEFT OUTER JOIN LGDAT.VEND ON 
		BTVEND = IGVEN#
	LEFT OUTER JOIN LGDAT.CONT ON
		IFCOM# = IGCOM# AND
		IFBNK# = IGBNK#
	LEFT OUTER JOIN LGDAT.AVTX ON
		AVTCHC = IGCOM# AND
		AVTCHB = IGBNK# AND
		AVTCHQ = IGCHQ# AND
		AVTTYP IN (' 4',' 5') 
	LEFT OUTER JOIN LGDAT.VCHR ON
		IDCOM# = IGCOM# AND
		IDVCH# = AVTVH# AND
		IDBNK# = IGBNK#
	LEFT OUTER JOIN LGDAT.OPEN ON	
		FHCOM# = IDCOM# AND
		FHBANK = IDBNK# AND
		FHVCH# = IDVCH#
	LEFT OUTER JOIN RLARP.FFSBGLR1 ON
		MODULE = 'APVN' AND
		CUSKEY1 = DIGITS(AVTVH#) AND
		SUBSTR(ACCT,1,2) = IGCOM# AND 
		PERD = DIGITS(IDFISY)||DIGITS(IDFISP) AND
		ACCT <>  IFCOM#||DIGITS(IFAPGL)
	LEFT OUTER JOIN 
	(
		SELECT DISTINCT
			YACOMP||DIGITS(Y1PRVR) PPVG, YACOMP||CASE YAACRL WHEN 0 THEN SUBSTR(A249,228,10) ELSE DIGITS(YAACRL) END ACCG
		FROM 
			LGDAT.GLIE
			LEFT OUTER JOIN LGDAT.PLNT ON
				YAPLNT = Y1PLNT
			LEFT OUTER JOIN LGDAT.NAME ON
				A7 = 'C0000'||YACOMP
	) GS ON
		PPVG = ACCT
	LEFT OUTER JOIN LGDAT.MAST ON
		AZCOMP||DIGITS(AZGL#1)||DIGITS(AZGL#2) = COALESCE(ACCG,ACCT)
	LEFT OUTER JOIN LGDAT.FGRP ON
		AZGROP = BQ1GRP
	LEFT OUTER JOIN LGDAT.GGTP ON
		D35GCDE = AZFUT3
	LEFT OUTER JOIN 
	(
		SELECT '1103040' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1 UNION ALL
		SELECT '2101020' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1 UNION ALL
		SELECT '5401060' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1
	) RM ON
		RM.FGRP = AZGROP
WHERE
	IESTS = 'O' AND
	IECOM# <> 66 AND
	IEBNK# <> 'P'
ORDER BY 
	IGCHQ#