SELECT
	'UNVOUCHERED' SRCE,
	KRRDAT,
	COALESCE(KRRDAT + PAYDAYS DAYS,PAYDATE) DUE_DATE,
	KRCOM#,
	KRVEN#,
	BTBANK,
	KRPO#,
	KRRKEY,
	KRDESC,
	KREXT,
	SUBSTRING(DIGITS(KRIVYR),3,2)||DIGITS(KRIVPR) PERD,
	KACURR,
	KRCOM#||DIGITS(KRGLEX) ACCT,
	KREXT,
	AZGROP,
	COALESCE(RM.DESCR,BQ1TITL) FGRP,
	D35DES2,
	D35USR3
FROM
	LGDAT.PORCAP C
	INNER JOIN LGDAT.VEND ON
		BTVEND = KRVEN#
	LEFT OUTER JOIN LGDAT.MAST ON
		AZCOMP||DIGITS(AZGL#1)||DIGITS(AZGL#2) = KRCOM#||DIGITS(KRGLEX)
	LEFT OUTER JOIN
		(
			SELECT '1103040' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1 UNION ALL
			SELECT '2101020' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1 UNION ALL
			SELECT '5401060' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1
		) RM ON
		RM.FGRP = AZGROP
	LEFT OUTER JOIN LGDAT.FGRP ON
		BQ1GRP = AZGROP
	LEFT OUTER JOIN LGDAT.POH ON		
		KAPO# = KRPO#
	LEFT OUTER JOIN
	(
		SELECT 
			LTRIM(RTRIM(A9)) TERM, 
			LTRIM(RTRIM(A30)) DESCR, 
			FLOAT(SUBSTR(A215,10,3)) PAYPERC, 
			CASE INT(SUBSTR(A215,28,6)) WHEN 0 THEN '' ELSE '20'||SUBSTR(A215,32,2)||'-'||SUBSTR(A215,28,2)||'-'||SUBSTR(A215,30,2) END PAYDATE, 
			INT(SUBSTR(A215,64,3)) PAYDAYS, 
			ROUND(FLOAT(SUBSTR(A215,102,4))/FLOAT(10000),2) DISCP, 
			INT(SUBSTR(A215,84,3)) DISCDAYS ,
			-MIN(
				FLOAT(
					(
						30.0-
						CASE 
							CASE INT(SUBSTR(A215,28,6)) 
								WHEN 0 THEN '' 
								ELSE '20'||SUBSTR(A215,32,2)||'-'||SUBSTR(A215,28,2)||'-'||SUBSTR(A215,30,2) 
							END 
						WHEN '' THEN INT(SUBSTR(A215,64,3)) 
						ELSE 
							DAYS(
							CASE INT(SUBSTR(A215,28,6)) 
								WHEN 0 THEN '' 
								ELSE '20'||SUBSTR(A215,32,2)||'-'||SUBSTR(A215,28,2)||'-'||SUBSTR(A215,30,2) 
							END
							) - 
							DAYS(
								CURRENT_DATE
							) 
						END
					)/30.0
				)*.01,
				FLOAT(30.0 - INT(SUBSTR(A215,84,3)))/30.0*.01-COALESCE(ROUND(FLOAT(SUBSTR(A215,102,4))/FLOAT(10000),2),0.0)
			) VATPWACC
		FROM 
			LGDAT.CODE 
		WHERE 
			A2 = 'NN'
	) TM ON	
		TM.TERM = KATRMC
	LEFT OUTER JOIN LGDAT.GGTP ON		
		D35GCDE = AZFUT3
WHERE
	SUBSTRING(DIGITS(KRIVYR),3,2)||DIGITS(KRIVPR) >= '1503'