SELECT
	SUBSTR(ACCT,1,2) COMP,
	MODULE, 
	COALESCE(ACCG,ACCT) ACCT, 
	CUSVEND,
	D.AMT,
	AZGROP FGRP, 
	COALESCE(RM.DESCR,BQ1TITL) FGRP_DESCR, 
	D35DES2, 
	D35USR3
FROM
	RLARP.FFSBGLR1 D 
	LEFT OUTER JOIN 
	---------------------cross reference PPV account to inventory account----------------------------------------
	(
		SELECT DISTINCT
			YACOMP||DIGITS(Y1PRVR) PPVG, YACOMP||CASE YAACRL WHEN 0 THEN SUBSTR(A249,228,10) ELSE DIGITS(YAACRL) END ACCG
		FROM 
			LGDAT.GLIE
			LEFT OUTER JOIN LGDAT.PLNT ON
				YAPLNT = Y1PLNT
			LEFT OUTER JOIN LGDAT.NAME ON
				A7 = 'C0000'||YACOMP
	) GS ON
		PPVG = ACCT
	LEFT OUTER JOIN LGDAT.MAST ON
		AZCOMP||DIGITS(AZGL#1)||DIGITS(AZGL#2) = COALESCE(ACCG,ACCT)
	LEFT OUTER JOIN LGDAT.FGRP ON
		AZGROP = BQ1GRP
	LEFT OUTER JOIN LGDAT.GGTP ON
		D35GCDE = AZFUT3
	--------------------cross reference material related account groups to materials-----------------------------
	LEFT OUTER JOIN 
		(
			SELECT '1103040' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1 UNION ALL
			SELECT '2101020' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1 UNION ALL
			SELECT '5401060' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1
		) RM ON
		RM.FGRP = AZGROP
WHERE	
	PERD = '1701' AND
	MODULE IN ('APVN','APAC') AND
	ACCT NOT IN (SELECT IFCOM#||DIGITS(IFAPGL) FROM LGDAT.CONT) AND
	SUBSTR(ACCT,1,2) <> '66'