SELECT
	AVTTYP, 
	IDAT, 
	DDAT, 
	AVTCO#, 
	VEND, 
	IDBNK#, 
	AVTVH#, 
	IDINV#, 
	IDVDES, 
	OP.AMT, 
	OP.PERD, 
	FHCURR, 
	MODULE, 
	BATCH, 
	TDATE, 
	PDATE, 
	COALESCE(ACCG,ACCT) ACCT, 
	D.AMT,
	PROJ,
	USRN,
	CUSKEY1, 
	CUSKEY2, 
	CUSKEY3, 
	CUSVEND,
	RECID,
	COALESCE(D.AMT,OP.AMT) AMT,
	AZGROP FGRP, 
	COALESCE(RM.DESCR,BQ1TITL) FGRP_DESCR, 
	D35DES2, 
	D35USR3
FROM
	---------------ap balance as of fiscal period----------------------
	(
		-------------------transactions since target---------------
		SELECT
			AVTTYP, CHAR(FHIDAT) IDAT, CHAR(FHDDAT) DDAT, AVTCO#, IDVEN#||' - '||BTNAME VEND, IDBNK#, DIGITS(AVTVH#) AVTVH#, IDINV#, IDVDES, 
			AVTVAM* CASE AVTTYP WHEN 1 THEN -1 WHEN 7 THEN -1 ELSE 1 END AMT, 
			DIGITS(IDFISY)||DIGITS(IDFISP) AS PERD, FHCURR
		FROM
			LGDAT.AVTX 
			LEFT OUTER JOIN LGDAT.VCHR ON
				IDCOM# = AVTCO# AND
				IDVCH# = AVTVH#
			LEFT OUTER JOIN LGDAT.VEND ON
				BTVEND = IDVEN#
			LEFT OUTER JOIN LGDAT.OPEN ON
				FHCOM# = AVTCO# AND
				FHVCH# = AVTVH#
		WHERE
			AVTFIS > '20'||'1701' AND DIGITS(IDFISY)||DIGITS(IDFISP) <= '1701'

		UNION ALL
		
		------------------current open balance--------------------
		SELECT
			'OPEN' AVTTYP,
			CHAR(FHIDAT) IDAT, 
			CHAR(FHDDAT) DDAT,
			FHCOM# AVTCO#,  
			RTRIM(FHVEN#)||' - '||RTRIM(BTNAME) VEND,
			FHBANK IDBNK#,
			FHVCH# AVTVH#,
			FHINV# AS IDINV#, 
			FHVDES IDVDES,
			FHCBAL AMT,
			DIGITS(IDFISY)||DIGITS(IDFISP) AS PERD, FHCURR
		FROM
			LGDAT.OPEN
			LEFT OUTER JOIN LGDAT.VEND ON
				BTVEND = FHVEN#
			LEFT OUTER JOIN LGDAT.VCHR ON
				IDVCH# = FHVCH# AND
				IDCOM# = FHCOM# AND
				IDBNK# = FHBANK AND
				IDFISY = FHPYY AND
				IDFISP = FHPPER
		WHERE
			FHCBAL <> 0 AND DIGITS(FHPYY)||DIGITS(FHPPER) >= '0901' AND
			DIGITS(FHPYY)||DIGITS(FHPPER) <= '1701'
	) OP
	LEFT OUTER JOIN LGDAT.CONT ON
		IFCOM# = AVTCO# AND
		IFBNK# = IDBNK#
	LEFT JOIN RLARP.FFSBGLR1 D ON
		MODULE = 'APVN' AND
		CUSKEY1 = DIGITS(AVTVH#) AND
		SUBSTR(ACCT,1,2) = AVTCO# AND
		D.PERD = OP.PERD AND
		--SUBSTR(D.ACCT,7,4) = '1690' AND
		ACCT <>  IFCOM#||DIGITS(IFAPGL)
	LEFT OUTER JOIN 
	---------------------cross reference PPV account to inventory account----------------------------------------
	(
		SELECT DISTINCT
			YACOMP||DIGITS(Y1PRVR) PPVG, YACOMP||CASE YAACRL WHEN 0 THEN SUBSTR(A249,228,10) ELSE DIGITS(YAACRL) END ACCG
		FROM 
			LGDAT.GLIE
			LEFT OUTER JOIN LGDAT.PLNT ON
				YAPLNT = Y1PLNT
			LEFT OUTER JOIN LGDAT.NAME ON
				A7 = 'C0000'||YACOMP
	) GS ON
		PPVG = ACCT
	LEFT OUTER JOIN LGDAT.MAST ON
		AZCOMP||DIGITS(AZGL#1)||DIGITS(AZGL#2) = COALESCE(ACCG,ACCT)
	LEFT OUTER JOIN LGDAT.FGRP ON
		AZGROP = BQ1GRP
	LEFT OUTER JOIN LGDAT.GGTP ON
		D35GCDE = AZFUT3
	--------------------cross reference material related account groups to materials-----------------------------
	LEFT OUTER JOIN 
		(
			SELECT '1103040' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1 UNION ALL
			SELECT '2101020' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1 UNION ALL
			SELECT '5401060' FGRP, 'MATERIALS' DESCR FROM SYSIBM.SYSDUMMY1
		) RM ON
		RM.FGRP = AZGROP
		