------CHECKS-----
/*
SELECT 
	RTRIM(LTRIM(CUSKEY2)) CHECKN, SUM(AMT)
FROM
	FFSBGLR1
WHERE
	PERD = '1605' AND
	(MODULE = 'APCQ' OR (MODULE = 'GJJB' AND SUBSTRING(CUSKEY4,2,3) IN  ('510','511','512'))) AND
	SUBSTRING(ACCT,7,4) = '1010'
GROUP BY
	RTRIM(LTRIM(CUSKEY2))
*/

-----CHECK RUNS----------
/*
SELECT 
	RTRIM(LTRIM(CUSKEY1)) CHKRUN, SUM(AMT)
FROM
	FFSBGLR1
WHERE
	PERD = '1605' AND
	MODULE = 'APCQ' AND
	SUBSTRING(ACCT,7,4) = '1010'
GROUP BY
	RTRIM(LTRIM(CUSKEY1))
*/


-----------AR Batches-------------------------
/*
SELECT 
	RTRIM(LTRIM(CUSKEY3)) CHKRUN, SUM(AMT)
FROM
	FFSBGLR1
WHERE
	PERD = '1605' AND
	MODULE = 'ARRC' AND
	SUBSTRING(ACCT,7,4) = '1010'
GROUP BY
	RTRIM(LTRIM(CUSKEY3))
HAVING
	SUM(AMT) <> 0
*/

----------VENDOR SPECIFIC-------------------------------------
/*
SELECT 
	RTRIM(LTRIM(CUSKEY1)) CHKRUN, RTRIM(LTRIM(CUSVEND)) VEND, SUM(AMT)
FROM
	FFSBGLR1
WHERE
	PERD = '1605' AND
	MODULE = 'APCQ' AND
	SUBSTRING(ACCT,7,4) = '1010'
GROUP BY
	RTRIM(LTRIM(CUSKEY1)), RTRIM(LTRIM(CUSVEND))
*/