SELECT
	NWPLNT, DIGITS(NWFSYY)||DIGITS(NWFSPP) PERD, WRKO, BTID, 
	COALESCE(QM.TIPENT, PM.OEPENT, Q.TIPENT, P.OEPENT) MPENT,
	ADEP, ARSC,	
	CASE SRCE
		WHEN 'RPRM' THEN UIPART
		WHEN 'RPRQ' THEN Q.TIPART
		WHEN 'RPRP' THEN P.OEPART
	END P_PART,
	PART C_PART,
	CASE SRCE
		WHEN 'RPRM' THEN UIRQBY
		WHEN 'RPRQ' THEN 
			CASE WHEN Q.TIQTYP < 0 THEN 
				CASE WHEN AMNT < 0 THEN 'B' ELSE 'R' END
			ELSE
				CASE WHEN AMNT < 0 THEN 'R' ELSE 'B' END
			END
		WHEN 'RPRP' THEN 
			CASE WHEN P.OESQTY < 0 THEN 
				CASE WHEN AMNT < 0 THEN 'B' ELSE 'R' END
			ELSE
				CASE WHEN AMNT < 0 THEN 'R' ELSE 'B' END
			END
	END RQBY,
	RPLN,
	SUM(CASE ACTN
		WHEN 'SBG' THEN PQTY
		WHEN 'SBS' THEN PQTY
		ELSE 0
	END) SQTY,
	SUM(CASE ACTN
		WHEN 'SBG' THEN AMNT
		WHEN 'SBS' THEN AMNT
		ELSE 0
	END) SCST,
	SUM(CASE ACTN
		WHEN 'ABT' THEN PQTY
		ELSE 0
	END) AQTY,
	SUM(CASE ACTN
		WHEN 'ABT' THEN AMNT
		ELSE 0
	END) ACST
FROM
	LGDAT.RPRH
	INNER JOIN QGPL.FFPDGLR1 G ON
		NWBTID = BTID
	LEFT OUTER JOIN LGDAT.RPRM M ON
		G.SRCE = 'RPRM' AND
		M.UIBTID = G.BTID AND
		M.UIENT# = G.ENT#
	LEFT OUTER JOIN LGDAT.RPRQ Q ON
		G.SRCE = 'RPRQ' AND
		Q.TIBTID = G.BTID AND
		Q.TIENT# = G.ENT#
	LEFT OUTER JOIN LGDAT.RPRP P ON
		G.SRCE = 'RPRP' AND
		P.OEBTID = G.BTID AND
		P.OEENT# = G.ENT#
	LEFT OUTER JOIN LGDAT.RPRQ QM ON
		QM.TIBTID = M.UIBTID AND
		QM.TIENT# = M.UIPENT
	LEFT OUTER JOIN LGDAT.RPRP PM ON
		PM.OEBTID = UIBTID AND
		PM.OEENT# = UIPENT
WHERE
	DIGITS(NWFSYY)||DIGITS(NWFSPP) = '1508' AND
	BTID = 340302 AND
	ACTN IN ('SBG','SBS','ABT') AND
	SUBSTR(ACCT,7,4) = '6400'
GROUP BY
	NWPLNT, DIGITS(NWFSYY)||DIGITS(NWFSPP), WRKO, BTID, 
	COALESCE(QM.TIPENT, PM.OEPENT, Q.TIPENT, P.OEPENT),
	ADEP, ARSC,	
	CASE SRCE
		WHEN 'RPRM' THEN UIPART
		WHEN 'RPRQ' THEN Q.TIPART
		WHEN 'RPRP' THEN P.OEPART
	END,
	PART,
	CASE SRCE
		WHEN 'RPRM' THEN UIRQBY
		WHEN 'RPRQ' THEN 
			CASE WHEN Q.TIQTYP < 0 THEN 
				CASE WHEN AMNT < 0 THEN 'B' ELSE 'R' END
			ELSE
				CASE WHEN AMNT < 0 THEN 'R' ELSE 'B' END
			END
		WHEN 'RPRP' THEN 
			CASE WHEN P.OESQTY < 0 THEN 
				CASE WHEN AMNT < 0 THEN 'B' ELSE 'R' END
			ELSE
				CASE WHEN AMNT < 0 THEN 'R' ELSE 'B' END
			END
	END,
	RPLN
FETCH FIRST 10 ROWS ONLY