CREATE OR REPLACE FUNCTION RLARP.FSTKBP ( 
	VPER VARCHAR(4) , 
	YYYYHMMHDD VARCHAR(10) ) 
	RETURNS TABLE ( 
	"PART" VARCHAR(20) , 
	PLNT VARCHAR(3) , 
	STOK VARCHAR(6) , 
	PERD VARCHAR(4) , 
	QTOH DOUBLE PRECISION , 
	COST DOUBLE PRECISION )   
	LANGUAGE SQL 
	SPECIFIC RLARP.FSTKBP 
	NOT DETERMINISTIC 
	READS SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DFTRDBCOL = *NONE , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	RETURN 
SELECT 
	BYPART PART , 
	BYPLNT PLNT , 
	BYSTOK STOK , 
	VPER PERD , 
	QTOH QTOG , 
	COALESCE ( FCOST , STDCOST ) COST 
FROM 
	( 
	SELECT 
		BYPLNT , BYPART , BYSTOK , SUM ( QTOH ) QTOH 
	FROM 
		( 
		SELECT 
			BYPLNT , BYPART , BYSTOK , 
			- SUM ( BYQTY * CASE BYACTN WHEN 'I' THEN - 1 ELSE 1 END ) QTOH 
		FROM 
			LGDAT . STKT STKT 
		WHERE 
			BYFSYY || DIGITS ( BYFSPR ) > '20' || VPER 
		GROUP BY 
			BYPLNT , BYPART , BYSTOK 
  
		UNION ALL 
  
		SELECT 
			BXPLNT BYPLNT , BXPART BYPART , BXSTOK BYSTOK , 
			SUM ( BXQTOH ) QTOH 
		FROM 
			LGDAT . STKB 
		WHERE 
			BXPART <> '' AND 
			BXQTOH <> 0 
		GROUP BY 
			BXPLNT , BXPART , BXSTOK 
		) X 
	GROUP BY 
		BYPLNT , BYPART , BYSTOK 
	) BEFP  ----BALANCE EFFECTIVE FISCAL PERIOD 
	LEFT OUTER JOIN RLARP . FFCOSTEFFD C ON 
		PART = BYPART AND 
		PLNT = BYPLNT AND 
		CHAR ( FDT ) || ' ' || CHAR ( FTM ) < YYYYHMMHDD || ' 23:59:59' AND 
		CHAR ( TDT ) || ' ' || CHAR ( TTM ) > YYYYHMMHDD || ' 23:59:59' 
	LEFT OUTER JOIN RLARP . VW_FFICSTX ON 
		V6PART = BYPART AND 
		V6PLNT = BYPLNT 

