CREATE OR REPLACE FUNCTION RLARP.STK_RF_A_USD(vPERD VARCHAR(4))
RETURNS TABLE
	(
		ACCT VARCHAR(12),
		PERD VARCHAR(4),
		GRP VARCHAR(255),
		VALUE_LOCAL FLOAT
	)
RETURN

SELECT	
	ACCT, PERD, GRP, VALUE_LOCAL, VALUE_LOCAL*RATE VALUE_USD
FROM
	(	
		SELECT
			YACOMP||Y1INVA ACCT, 
			--BYPART, BYPLNT, BYSTOK, 
			PERD, GRP, 
			--COST, BYQTY
			SUM(COST*BYQTY) VALUE_LOCAL
		FROM
			(
				SELECT 	
					BYPART, BYPLNT, BYSTOK, SUBSTR(DIGITS(BYFSYY),3,2)||DIGITS(BYFSPR) PERD, GRP, COALESCE(FCOST, STDCOST) COST,
					SUM(BYQTY*CASE BYACTN WHEN 'I' THEN -1 ELSE 1 END) BYQTY
				FROM 
					LGDAT.STKT T
					LEFT OUTER JOIN RLARP.FFSTGR ON
						SRC = UPPER(RTRIM(BYSRC)||SUBSTRING(LTRIM(BYREAS||BYDREF),1,3))
					LEFT OUTER JOIN RLARP.FFCOSTEFFD ON
						PART = BYPART AND
						PLNT = BYPLNT AND
						CHAR(FDT)||' '||CHAR(FTM) < CHAR(BYSDAT)||' '||CHAR(BYSTIM) AND
						CHAR(TDT)||' '||CHAR(TTM) > CHAR(BYSDAT)||' '||CHAR(BYSTIM)
					LEFT OUTER JOIN RLARP.VW_FFICSTX ON
						V6PART = BYPART AND
						V6PLNT = BYPLNT
				WHERE
					BYFSYY = '20'||SUBSTR(VPERD,1,2) AND
					BYFSPR = SUBSTR(VPERD,3,2)
				GROUP BY
					BYPART, BYPLNT, BYSTOK, SUBSTR(DIGITS(BYFSYY),3,2)||DIGITS(BYFSPR), GRP, COALESCE(FCOST, STDCOST)
				HAVING
					SUM(BYQTY*CASE BYACTN WHEN 'I' THEN -1 ELSE 1 END) <> 0
			) G
			INNER JOIN RLARP.VW_FFSTKMX ON
				AVPART = BYPART
			INNER JOIN LGDAT.PLNT ON
				YAPLNT = BYPLNT
			LEFT OUTER JOIN LGDAT.GLIE ON
				Y1GLEC = AVGLED AND
				Y1PLNT = BYPLNT
		GROUP BY
			YACOMP||Y1INVA, PERD, GRP

		UNION ALL

		SELECT
			YACOMP||Y1INVA ACCT, G.FSPR, 'COST ROLL' GRP, ROUND(SUM((TCOST-FCOST)*TQTY),2) VALUE_LOCAL
		FROM
			RLARP.VW_FFGLPD G
			INNER JOIN RLARP.VW_PRFSPR P ON
				P.COMP = G.COMP AND
				P.CURRP = G.FSPR
			INNER JOIN LGDAT.PLNT ON
				YACOMP = G.COMP
			INNER JOIN RLARP.FFCOSTEFFD C ON
				C.PLNT = YAPLNT AND
				C.TDT >= SDAT AND
				C.TDT <= EDAT
			INNER JOIN RLARP.VW_FFSTKMX ON
				AVPART = C.PART
			INNER JOIN LGDAT.GLIE ON
				Y1PLNT = C.PLNT AND
				Y1GLEC = AVGLED
		WHERE
			G.FSPR = VPERD AND
			TCOST-FCOST <> 0 AND
			TQTY <> 0
		GROUP BY
			YACOMP||Y1INVA, G.FSPR

		UNION ALL

		SELECT 
			YACOMP||Y1INVA ACCT, 
			CURRP,
			'OPEN' COMPONENT,
			ROUND(SUM(QTYOH*COST_EFF),2) VALUE_LOCAL	
		FROM 
			RLARP.FFSTKBP 
			INNER JOIN LGDAT.PLNT ON
				YAPLNT = PLNT
			INNER JOIN RLARP.VW_PRFSPR ON
				COMP = YACOMP AND
				PRIORP = PERD
			LEFT OUTER JOIN RLARP.VW_FFSTKMX ON
				AVPART = PART
			LEFT OUTER JOIN LGDAT.GLIE ON
				Y1PLNT = PLNT AND
				Y1GLEC = AVGLED
		WHERE
			CURRP = VPERD
		GROUP BY
			YACOMP||Y1INVA, CURRP

		UNION ALL

		SELECT 
			YACOMP||Y1INVA ACCT, 
			PERD,
			'END' COMPONENT,
			ROUND(SUM(QTYOH*COST_EFF),2) VALUE_LOCAL	
		FROM 
			RLARP.FFSTKBP 
			INNER JOIN LGDAT.PLNT ON
				YAPLNT = PLNT
			LEFT OUTER JOIN RLARP.VW_FFSTKMX ON
				AVPART = PART
			LEFT OUTER JOIN LGDAT.GLIE ON
				Y1PLNT = PLNT AND
				Y1GLEC = AVGLED
		WHERE
			PERD = VPERD
		GROUP BY
			YACOMP||Y1INVA, PERD
	) X
	LEFT OUTER JOIN LGDAT.MAST ON
		AZCOMP||DIGITS(AZGL#1)||DIGITS(AZGL#2)
	LEFT OUTER JOIN RLARP.FFCRET ON
		FCUR = AZFUT2 AND
		TCUR = 'US' AND
		RTYP = 'ME' AND
		PERD = X.PERD