SELECT
	NWPLNT,
	ADEP,
	PERD,
	SUM(STD_LAB) STD_LAB,
	SUM(ACT_LAB) ACT_LAB,
	SUM(STD_OVH) STD_OVH,
	SUM(ACT_OVH) ACT_OVH,
	SUM(STD_SCR) STD_SCR, 
	SUM(ACT_SCR) ACT_SCR,
	SUM(STD_BOM) STD_BOM,
	SUM(ACT_BOM) ACT_BOM,
	SUM(FPV) FPV
FROM
	(
	SELECT
		NWPLNT,
		ADEP,
		DIGITS(NWFSYY)||DIGITS(NWFSPP) PERD,
		SUM(
			CASE ACTN
				WHEN 'ALG' THEN AMNT
				WHEN 'ALS' THEN AMNT
				ELSE 0 
			END
		) STD_LAB,
		0 ACT_LAB,
		SUM(
			CASE ACTN
				WHEN 'AVG' THEN AMNT
				WHEN 'AVS' THEN AMNT
				WHEN 'AFG' THEN AMNT
				WHEN 'AFS' THEN AMNT
				ELSE 0
			END
		) STD_OVH,
		0 ACT_OVH,
		SUM(
			CASE ACTN
				WHEN 'ASG' THEN AMNT
				WHEN 'ASS' THEN AMNT
				ELSE 0 
			END
		) STD_SCR,
		SUM(
			CASE ACTN
				WHEN 'CPS' THEN AMNT
				ELSE 0
			END
		) ACT_SCR,
		SUM(
			CASE ACTN
				WHEN 'SBS' THEN AMNT
				WHEN 'SBG' THEN AMNT
				ELSE 0
			END
		) STD_BOM,
		SUM(
			CASE ACTN
				WHEN 'ABT' THEN AMNT
				ELSE 0
			END
		) ACT_BOM,
		SUM(
			CASE SUBSTR(ACCT,7,4)
				WHEN '1220' THEN AMNT
				ELSE 0
			END
		) FPV
			
	FROM 
		FANALDEV.FFPDGLR1 D 
		INNER JOIN LGDAT.RPRH H ON
			NWBTID = BTID
	WHERE
		NWFSYY = 16 AND
		ADEP IN ('15505','15205')
	GROUP BY
		NWPLNT,
		ADEP,
		DIGITS(NWFSYY)||DIGITS(NWFSPP)
		
	UNION ALL
	
	SELECT
		'1'||SUBSTR(ACCT,3,2) NWPLNT,
		'1'||SUBSTR(ACCT,3,4) ADEP,
		PERD,
		
		0 STD_LAB,
		
		SUM(
			CASE SUBSTR(AZGROP,1,5)
				WHEN '57010' THEN AMT
			END
		) ACT_LAB,
		
		0 STD_OVH,
		
		SUM(
			CASE SUBSTR(AZGROP,1,5)
				WHEN '57020' THEN AMT
			END
		) ACT_OVH,
		
		0 STD_SCR,
		0 ACT_SCR,
		0 STD_BOM,
		0 ACT_BOM,
		0 FPV
	
	FROM
		FANALDEV.FFSBGLR1
		INNER JOIN LGDAT.MAST ON
			AZCOMP||DIGITS(AZGL#1)||DIGITS(AZGL#2) = ACCT
	WHERE
		'1'||SUBSTR(ACCT,3,4) IN ('15205','15505') AND
		PERD >= '1601'
	GROUP BY
		'1'||SUBSTR(ACCT,3,2),
		'1'||SUBSTR(ACCT,3,4),
		PERD
	) X
GROUP BY
	NWPLNT,
	ADEP,
	PERD	