
INSERT INTO RLARP.FFORDD
SELECT
	------------------------status-------------------------------------------------------------------------
	F.FLAG, 
	CASE DDITST 
		WHEN 'C' THEN 
			CASE DDQTSI 
				WHEN 0 THEN 'CANCELED' 
				ELSE 'CLOSED' 
			END 
		ELSE 
			CASE F.FLAG
				WHEN 'SHIPMENT' THEN 'CLOSED' 
				ELSE CASE WHEN DDQTSI >0 THEN 'BACKORDER' ELSE 'OPEN' END 
			END 
	END CALC_STATUS, 
	-----------------------id's and flags------------------------------------------------------------------
	DDORD#, DDITM#, FGBOL#, FGENT#, DIINV#, DILIN#, DDODAT, FESDAT, FESIND, DHIDAT, DHPOST, 
	------------------------periods------------------------------------------------------------------------
	SUBSTR(CHAR(DCODAT),3,2)||SUBSTR(CHAR(DCODAT),6,2) CAPR_ORD,
	GF.FSPR FSPR_ORD,
	SUBSTR(CHAR(DDQDAT),3,2)||SUBSTR(CHAR(DDQDAT),6,2) CAPR_REQ,
	DIGITS(DHARYR)||DIGITS(DHARPR) FSPR_INV,
	------------------------attributes---------------------------------------------------------------------
	COALESCE(DHPLNT,FGPLNT,SUBSTR(DDSTKL,1,3)) PLNT,
	YACOMP COMP,
	DDPART PART,
	COALESCE(DCBCUS,DHBCS#) CUST_BILL,
	COALESCE(DCSCUS,DHSCS#) CUST_SHIP,
	COALESCE(DIGLCD, DDGLC) GL_CODE, 
	RTRIM(DCPROM) PROMO,
	CASE F.FLAG
		WHEN 'REMAINDER' THEN 
			DDQTOI-DDQTSI
		WHEN 'SHIPMENT' THEN
			FGQSHP*CASE FESIND WHEN 'Y' THEN 1 ELSE 0 END
	END FB_QTY,
	COALESCE(DHCURR,DCCURR) CURRENCY,
	CAST(COALESCE(
	CASE F.FLAG
		WHEN 'REMAINDER' THEN 
			--------remaining qty*calculated price per---------
			CAST(CASE COALESCE(DDQTOI,0) 
				WHEN 0 THEN 0 
				ELSE DDTOTI/DDQTOI 
			END AS FLOAT)*(DDQTOI - DDQTSI)
		WHEN 'SHIPMENT' THEN
			---------BOL quantity * calculated price per-------
			CAST(CASE COALESCE(DDQTOI,0)
				WHEN 0 THEN 0 
				ELSE DDTOTI/DDQTOI 
			END AS FLOAT)*COALESCE(FGQSHP*CASE FESIND WHEN 'Y' THEN 1 ELSE 0 END,DDQTSI)
	END,0) AS DEC(18,2)) FB_VAL_LOC
FROM
	----------------------Order Data-----------------------------
	LGDAT.OCRI 
	INNER JOIN LGDAT.OCRH ON 
		DCORD# = DDORD# 
	-----------------------BOL-----------------------------------
	LEFT OUTER JOIN LGDAT.BOLD ON 
		FGORD# = DDORD# AND 
		FGITEM = DDITM# 
	LEFT OUTER JOIN LGDAT.BOLH ON 
		FEBOL# = FGBOL#
	----------------------Invoicing------------------------------
	LEFT OUTER JOIN LGDAT.OID ON 
		DIINV# = FGINV# AND 
		DILIN# = FGLIN# 
	LEFT OUTER JOIN LGDAT.OIH ON 
		DHINV# = DIINV# 
	LEFT OUTER JOIN LGDAT.PLNT ON
		YAPLNT = COALESCE(DHPLNT,FGPLNT,SUBSTR(DDSTKL,1,3))
	LEFT OUTER JOIN RLARP.VW_FFGLPD GF ON
		GF.COMP = YACOMP AND
		GF.SDAT <= DCODAT AND
		GF.EDAT >= DCODAT
	CROSS JOIN TABLE( VALUES
		('REMAINDER'),
		('SHIPMENT')
	) AS F(FLAG)
WHERE
	DCODAT >= '2013-01-01' AND
	DCODAT <= '2013-12-31' AND
	(
		(F.FLAG = 'REMAINDER' AND DDQTOI-DDQTSI <> 0) OR 
		(F.FLAG = 'SHIPMENT' AND FGQSHP*CASE FESIND WHEN 'Y' THEN 1 ELSE 0 END<>0)
	);
	
	
SELECT
	FLAG, 
	CALC_STATUS,
	CAPR_ORD,
	'20'||SUBSTR(CAPR_ORD,1,2) CAYR_ORD,
	ICP.CAPR CAPR_INV, 
	CASE CALC_STATUS
			WHEN 'OPEN' THEN MAX(CAPR_REQ, SUBSTR(CHAR(CURRENT_DATE),3,2)||SUBSTR(CHAR(CURRENT_DATE),6,2))
			WHEN 'BACKORDER' THEN MAX(CAPR_REQ, SUBSTR(CHAR(CURRENT_DATE),3,2)||SUBSTR(CHAR(CURRENT_DATE),6,2))
			WHEN 'CANCELED' THEN '0000'
			WHEN 'CLOSED' THEN COALESCE(ICP.CAPR,'0000')
	END	CAPR_MOD,
	'20'||SUBSTR(CASE CALC_STATUS
			WHEN 'OPEN' THEN MAX(CAPR_REQ, SUBSTR(CHAR(CURRENT_DATE),3,2)||SUBSTR(CHAR(CURRENT_DATE),6,2))
			WHEN 'BACKORDER' THEN MAX(CAPR_REQ, SUBSTR(CHAR(CURRENT_DATE),3,2)||SUBSTR(CHAR(CURRENT_DATE),6,2))
			WHEN 'CANCELED' THEN '0000'
			WHEN 'CLOSED' THEN COALESCE(ICP.CAPR,'0000')
	END,1,2) CAYR_MOD,
	GL_CODE,
	PROMO,
	SUM(FX.RATE*FB_VAL_LOC) FB_VAL_USD, 
	BQ1GRP||' - '||RTRIM(BQ1TITL) FGRP,
	GLEC, MAJG, MING, MAJS, MINS, 
	BC.BVCLAS CUST_BILL_CLASS,
	SC.BVCLAS CUST_SHIP_CLASS
FROM
	RLARP.FFORDD D
	------------------CALENDAR PERIOD OF INVOICE----------------
	LEFT OUTER JOIN RLARP.VW_FFGLPD ICP ON
		ICP.COMP = D.COMP AND
		ICP.FSPR = FSPR_INV
	LEFT OUTER JOIN RLARP.FFCRET FX ON
		FX.PERD = CASE CALC_STATUS WHEN 'OPEN' THEN SUBSTR(CHAR(CURRENT_DATE),3,2)||SUBSTR(CHAR(CURRENT_DATE),6,2) ELSE COALESCE(FSPR_INV, CAPR_ORD) END AND
		FX.FCUR = D.CURRENCY AND
		FX.TCUR = 'US' AND
		FX.RTYP = 'MA'
	LEFT OUTER JOIN RLARP.VW_FFITEMM I ON
		I.ITEM = D.PART
	LEFT OUTER JOIN LGDAT.CUST BC ON
		BC.BVCUST = D.CUST_BILL
	LEFT OUTER JOIN LGDAT.CUST SC ON
		SC.BVCUST = D.CUST_SHIP
	LEFT OUTER JOIN LGDAT.ARMASC ON
		ZWCOMP = BC.BVCOMP AND
		ZWKEY1 = BC.BVARCD AND
		ZWKEY2 = GL_CODE
	LEFT OUTER JOIN LGDAT.MAST ON
		AZCOMP||DIGITS(AZGL#1)||DIGITS(AZGL#2) = ZWSAL#
	LEFT OUTER JOIN LGDAT.FGRP ON
		BQ1GRP = AZGROP
GROUP BY
	FLAG, 
	CALC_STATUS,
	CAPR_ORD,
	'20'||SUBSTR(CAPR_ORD,1,2),
	ICP.CAPR, 
	CASE CALC_STATUS
			WHEN 'OPEN' THEN MAX(CAPR_REQ, SUBSTR(CHAR(CURRENT_DATE),3,2)||SUBSTR(CHAR(CURRENT_DATE),6,2))
			WHEN 'BACKORDER' THEN MAX(CAPR_REQ, SUBSTR(CHAR(CURRENT_DATE),3,2)||SUBSTR(CHAR(CURRENT_DATE),6,2))
			WHEN 'CANCELED' THEN '0000'
			WHEN 'CLOSED' THEN COALESCE(ICP.CAPR,'0000')
	END,
	'20'||SUBSTR(CASE CALC_STATUS
			WHEN 'OPEN' THEN MAX(CAPR_REQ, SUBSTR(CHAR(CURRENT_DATE),3,2)||SUBSTR(CHAR(CURRENT_DATE),6,2))
			WHEN 'BACKORDER' THEN MAX(CAPR_REQ, SUBSTR(CHAR(CURRENT_DATE),3,2)||SUBSTR(CHAR(CURRENT_DATE),6,2))
			WHEN 'CANCELED' THEN '0000'
			WHEN 'CLOSED' THEN COALESCE(ICP.CAPR,'0000')
	END,1,2),
	GL_CODE,
	PROMO,
	BQ1GRP||' - '||RTRIM(BQ1TITL),
	GLEC, MAJG, MING, MAJS, MINS, 
	BC.BVCLAS,
	SC.BVCLAS