SELECT
	T.*
FROM
	QGPL.FFSBGLR1 T
	INNER JOIN LGDAT.MAST M ON --ACOUNT MASTER
		M.ACCT = T.ACCT
	LEFT OUTER JOIN LGDAT.GGTP C ON	--GL CATEGORY CODE MASTER
		C.GLCD = M.GLCD
	LEFT OUTER JOIN LGDAT.FGRP G ON --ACCOUNT GROUP MASTER
		G.GRP = dbo.RETURN_NONBLANK(C.U2,M.FGRP,'')
	LEFT OUTER JOIN FANALYSIS.VW_GLPD P ON	--PERIOD MASTER
		P.FSPR = T.PERD AND
		P.COMP = SUBSTR(T.ACCT,1,2)
	LEFT OUTER JOIN FANALYSIS.FFCRET F ON				--EXCHANGE RATES
		F.FCUR = M.CURR AND
		F.TCUR = 'US' AND
		F.PERD = T.PERD AND
		F.RTYP = CASE WHEN M.ATYP <= '3' THEN 'ME' ELSE 'MA' END
	LEFT OUTER JOIN LGDAT.VEND ON
		CUSVEND = BTVEND
	LEFT OUTER JOIN LGDAT.CUST ON
		CUSCUST = BVCUST
WHERE
	PERD = '1603' AND
	SUBSTR(AZGROP,1,5) IN ('61520','61530')
	SUBSTRING(T.ACCT,1,2) > '19'
