SELECT TOP 100
	PERD,
	NWPLNT,
	ADEPT,
	ARESC,
	STAT,
	RPLN,
	OPTR,
	SDEPT,
	SRESC,
	RRATE,
	SUM(OAQTYG) QTYG,
	SUM(OAQTYS) QTYS,
	SUM(STIME) STIME,
	SUM(STIMEG) STIMEG,
	SUM(RTIME) RTIME,
	SUM(DTIME) DTIME,
	SUM(CASE SUBSTRING(CODE, 1, 2)
			WHEN 'B2'
				THEN DTIME
			ELSE 0
			END) PDTIME,
	SUM(ABSLAB) ABSLAB,
	SUM(ABSOVH) ABSOVH,
	CODE,
	SUM(FPV) FPV
FROM (
	-----------------------------DOWNTIME--------------------------------------------
	SELECT NWFSYY + FORMAT(NWFSPP,'00') PERD,
		NWPLNT,
		NXDEPT ADEPT,
		NXRESC ARESC,
		'' STAT,
		'' RPLN,
		0 OPTR,
		'' SDEPT,
		'' SRESC,
		0 RRATE,
		0 OAQTYG,
		0 OAQTYS,
		0 STIME,
		0 STIMEG,
		0 RTIME,
		SUM(NXTIME) DTIME,
		0 ABSLAB,
		0 ABSOVH,
		RTRIM(NXINDC) + ' - ' + RTRIM(AFDES1) CODE,
		0 FPV
	FROM LGDAT.RPRH
	INNER JOIN LGDAT.RPRD
		ON NWBTID = NXBTID
	LEFT JOIN LGDAT.INDLBR
		ON AFCODE = NXINDC
	WHERE NWFSYY >= 15
	GROUP BY NWFSYY + FORMAT(NWFSPP,'00'),
		NWPLNT,
		NXDEPT,
		NXRESC,
		RTRIM(NXINDC) + ' - ' + RTRIM(AFDES1
		--11 SEC
	
	UNION ALL
	
	--------------------------------RUN TIME----------------------------------------
	SELECT NWFSYY + FORMAT(NWFSPP,'00') PERD,
		NWPLNT,
		OADEPT ADEPT,
		OARESC ARESC,
		V6STAT STAT,
		V6RPLN RPLN,
		V6OPTR OPTR,
		AODEPT SDEPT,
		AORESC SRESC,
		CASE ABVBRD
			WHEN 0
				THEN ISNULL(AAVBRD, 0)
			ELSE ISNULL(ABVBRD, 0)
			END + CASE ABBRDR
			WHEN 0
				THEN ISNULL(AABRDR, 0)
			ELSE ISNULL(ABBRDR, 0)
			END RRATE,
		0 OAQTYG,
		0 OAQTYS,
		0 STIME,
		0 STIMEG,
		SUM(OATIME) RTIME,
		0 DTIME,
		0 ABSLAB,
		0 ABSOVH,
		'02 - RUN' CODE,
		0 FPV
	FROM LGDAT.RPRR
	INNER JOIN LGDAT.RPRH
		ON NWBTID = OABTID
	LEFT JOIN LGDAT.METHDR
		ON AOPART = OAPART
			AND AOPLNT = NWPLNT
			AND AOSEQ# = OASEQ#
	LEFT JOIN LGDAT.PUNIT C1
		ON C1.IHPART = OAPART
			AND C1.IHUNT2 = OAUNIT
			AND C1.IHUNT1 = AOUNIT
	LEFT JOIN LGDAT.PUNIT C2
		ON C2.IHPART = OAPART
			AND C2.IHUNT1 = OAUNIT
			AND C2.IHUNT2 = AOUNIT
	LEFT JOIN LGDAT.RESRE
		ON ABDEPT = AODEPT
			AND ABRESC = AORESC
	LEFT JOIN LGDAT.DEPTS
		ON ABDEPT = AADEPT
	LEFT JOIN LGDAT.STKA
		ON V6PART = OAPART
			AND V6PLNT = NWPLNT
	WHERE NWFSYY >= 15
	GROUP BY NWFSYY + FORMAT(NWFSPP,'00'),
		NWPLNT,
		OADEPT,
		OARESC,
		AORESC,
		AODEPT,
		V6STAT,
		V6RPLN,
		V6OPTR,
		CASE ABVBRD
			WHEN 0
				THEN ISNULL(AAVBRD, 0)
			ELSE ISNULL(ABVBRD, 0)
			END + CASE ABBRDR
			WHEN 0
				THEN ISNULL(AABRDR, 0)
			ELSE ISNULL(ABBRDR, 0)
			END
	--13 sec

	UNION ALL
	
	-------------------------------------EARNED HOURS------------------------------------------------
	SELECT NWFSYY + FORMAT(NWFSPP,'00') PERD,
		NWPLNT,
		OADEPT ADEPT,
		OARESC ARESC,
		V6STAT STAT,
		V6RPLN RPLN,
		V6OPTR OPTR,
		AODEPT SDEPT,
		AORESC SRESC,
		(
			CASE ABVBRD
				WHEN 0
					THEN ISNULL(AAVBRD, 0)
				ELSE ISNULL(ABVBRD, 0)
				END + CASE ABBRDR
				WHEN 0
					THEN ISNULL(AABRDR, 0)
				ELSE ISNULL(ABBRDR, 0)
				END
			) RRATE,
		SUM(OAQTYG) OAQTYG,
		SUM(OAQTYS) OAQTYS,
		SUM((
				CASE ISNULL(AORUNS, 0)
					WHEN 0
						THEN 0
					ELSE 1 / AORUNS
					END + AOSETP / 1000000
				) * (OAQTYG + OAQTYS) * COALESCE((C1.IHCNV1 / C1.IHCNV2), (C2.IHCNV2 / C2.IHCNV1), 1)) STIME,
		SUM((
				CASE ISNULL(AORUNS, 0)
					WHEN 0
						THEN 0
					ELSE 1 / AORUNS
					END + AOSETP / 1000000
				) * (OAQTYG) * COALESCE((C1.IHCNV1 / C1.IHCNV2), (C2.IHCNV2 / C2.IHCNV1), 1)) STIMEG,
		0 RTIME,
		0 DTIME,
		SUM(CASE ABLABR
				WHEN 0
					THEN ISNULL(AASTDR, 0)
				ELSE ISNULL(ABLABR, 0)
				END * (
				CASE ISNULL(AORUNS, 0)
					WHEN 0
						THEN 0
					ELSE 1 / AORUNS
					END * AO#MEN / AO#MCH + AOSETP * AOSCRW / 1000000
				) * (OAQTYG + OAQTYS) * COALESCE((C1.IHCNV1 / C1.IHCNV2), (C2.IHCNV2 / C2.IHCNV1), 1)) ABSLAB,
		SUM((
				CASE ABVBRD
					WHEN 0
						THEN ISNULL(AAVBRD, 0)
					ELSE ISNULL(ABVBRD, 0)
					END + CASE ISNULL(ABBRDR, 0)
					WHEN 0
						THEN ISNULL(AABRDR, 0)
					ELSE ISNULL(ABBRDR, 0)
					END
				) * (
				CASE ISNULL(AORUNS, 0)
					WHEN 0
						THEN 0
					ELSE 1 / AORUNS
					END + AOSETP / 1000000
				) * (OAQTYG + OAQTYS) * COALESCE((C1.IHCNV1 / C1.IHCNV2), (C2.IHCNV2 / C2.IHCNV1), 1)) ABSOVH,
		'01 - EARNED' CODE,
		0 FPV
	FROM LGDAT.RPRR
	INNER JOIN LGDAT.RPRH
		ON NWBTID = OABTID
	LEFT JOIN LGDAT.METHDR
		ON AOPART = OAPART
			AND AOPLNT = NWPLNT
			AND AOSEQ# = OASEQ#
	LEFT JOIN LGDAT.PUNIT C1
		ON C1.IHPART = OAPART
			AND C1.IHUNT2 = OAUNIT
			AND C1.IHUNT1 = AOUNIT
	LEFT JOIN LGDAT.PUNIT C2
		ON C2.IHPART = OAPART
			AND C2.IHUNT1 = OAUNIT
			AND C2.IHUNT2 = AOUNIT
	LEFT JOIN LGDAT.RESRE
		ON ABDEPT = AODEPT
			AND ABRESC = AORESC
	LEFT JOIN LGDAT.DEPTS
		ON ABDEPT = AADEPT
	LEFT JOIN LGDAT.STKA
		ON V6PART = OAPART
			AND V6PLNT = NWPLNT
	WHERE NWFSYY >= 15
		AND AORESC <> ''
	GROUP BY NWFSYY + FORMAT(NWFSPP,'00'),
		NWPLNT,
		OADEPT,
		OARESC,
		AORESC,
		AODEPT,
		V6STAT,
		V6RPLN,
		V6OPTR,
		CASE ABVBRD
			WHEN 0
				THEN ISNULL(AAVBRD, 0)
			ELSE ISNULL(ABVBRD, 0)
			END + CASE ABBRDR
			WHEN 0
				THEN ISNULL(AABRDR, 0)
			ELSE ISNULL(ABBRDR, 0)
			END
			--21 sec
	
	UNION ALL
	
	---------------------------------------------FPV-------------------------------------------
	SELECT NWFSYY + FORMAT(NWFSPP,'00') PERD,
		NWPLNT,
		TIDEPT ADEPT,
		TIRESC ARESC,
		V6STAT STAT,
		V6RPLN RPLN,
		V6OPTR OPTR,
		'' SDEPT,
		'' SRESC,
		0 RRATE,
		0 OAQTYG,
		0 OAQTYS,
		0 STIME,
		0 STIMEG,
		0 RTIME,
		0 DTIME,
		0 ABSLAB,
		0 ABSOVH,
		'03 - FPV' CODE,
		SUM(TIQTYP * COALESCE((C1.IHCNV1 / C1.IHCNV2), (C2.IHCNV2 / C2.IHCNV1), 1) * COALESCE(CHSTCS, CGSTCS, Y0STCS)) FPV
	FROM LGDAT.RPRH
	INNER JOIN LGDAT.RPRQ
		ON TIBTID = NWBTID
	LEFT JOIN LGDAT.STKA
		ON V6PART = TIPART
			AND V6PLNT = NWPLNT
	LEFT JOIN LGDAT.ICSTP
		ON CHPART = TIPART
			AND CHPLNT = NWPLNT
	LEFT JOIN LGDAT.ICSTM
		ON CGPART = TIPART
			AND CGPLNT = NWPLNT
	LEFT JOIN LGDAT.ICSTR
		ON Y0PART = TIPART
			AND Y0PLNT = NWPLNT
	LEFT JOIN LGDAT.STKMM
		ON AVPART = TIPART
	LEFT JOIN LGDAT.STKMP
		ON AWPART = TIPART
	LEFT JOIN LGDAT.GLIE
		ON Y1GLEC = COALESCE(AWGLED, AVGLED)
			AND Y1PLNT = NWPLNT
	LEFT JOIN LGDAT.PLNT
		ON YAPLNT = NWPLNT
	LEFT JOIN LGDAT.PUNIT C1
		ON C1.IHPART = TIPART
			AND C1.IHUNT2 = TIUNIT
			AND C1.IHUNT1 = V6UNTI
	LEFT JOIN LGDAT.PUNIT C2
		ON C2.IHPART = TIPART
			AND C2.IHUNT1 = TIUNIT
			AND C2.IHUNT2 = V6UNTI
	WHERE NWFSYY >= 15
		AND TIQTYP <> 0
		AND SUBSTRING(FORMAT(YACOMP,'00') + FORMAT(Y1INVA,'00'), 7, 4) = '1220'
	GROUP BY NWFSYY + FORMAT(NWFSPP,'00'),
		NWPLNT,
		TIDEPT,
		TIRESC,
		V6STAT,
		V6RPLN,
		V6OPTR
		--18 sec
	
	UNION ALL
	
	SELECT NWFSYY + FORMAT(NWFSPP,'00') PERD,
		NWPLNT NWPLNT,
		UIDEPT ADEPT,
		UIRESC ARESC,
		V6STAT STAT,
		V6RPLN RPLN,
		V6OPTR OPTR,
		'' SDEPT,
		'' SRESC,
		0 RRATE,
		0 OAQTYG,
		0 OAQTYS,
		0 STIME,
		0 STIMEG,
		0 RTIME,
		0 DTIME,
		0 ABSLAB,
		0 ABSOVH,
		'03 - FPV' CODE,
		- SUM(UITQTY * CASE UIRQBY
				WHEN 'B'
					THEN - 1
				ELSE 1
				END * COALESCE(CHSTCS, CGSTCS, Y0STCS)) FPV
	FROM LGDAT.RPRH
	INNER JOIN LGDAT.RPRM
		ON UIBTID = NWBTID
	LEFT JOIN LGDAT.ICSTP
		ON CHPART = UIMTLP
			AND CHPLNT = NWPLNT
	LEFT JOIN LGDAT.ICSTM
		ON CGPART = UIMTLP
			AND CGPLNT = NWPLNT
	LEFT JOIN LGDAT.ICSTR
		ON Y0PART = UIMTLP
			AND Y0PLNT = NWPLNT
	LEFT JOIN LGDAT.STKMM
		ON AVPART = UIMTLP
	LEFT JOIN LGDAT.STKMP
		ON AWPART = UIMTLP
	LEFT JOIN LGDAT.GLIE
		ON Y1GLEC = COALESCE(AWGLED, AVGLED)
			AND Y1PLNT = NWPLNT
	LEFT JOIN LGDAT.PLNT
		ON YAPLNT = NWPLNT
	LEFT JOIN LGDAT.STKA
		ON V6PART = UIPART
			AND V6PLNT = NWPLNT
	WHERE NWFSYY >= 15
		AND UITQTY <> 0
		AND SUBSTRING(FORMAT(YACOMP,'00') + FORMAT(Y1INVA,'00'), 7, 4) = '1220'
	GROUP BY NWFSYY + FORMAT(NWFSPP,'00'),
		NWPLNT,
		UIDEPT,
		UIRESC,
		V6STAT,
		V6RPLN,
		V6OPTR
	) X
GROUP BY PERD,
	NWPLNT,
	ADEPT,
	ARESC,
	STAT,
	RPLN,
	OPTR,
	SDEPT,
	SRESC,
	RRATE,
	CODE