SELECT
	YACOMP||Y1INVA ACCT, 
	--BYPART, BYPLNT, BYSTOK, 
	PERD, GRP, 
	--COST, BYQTY
	SUM(VALUE_LOCAL) VALUE_LOCAL
FROM
	(
		SELECT 	
			BYPART, BYPLNT, BYSTOK, SUBSTR(DIGITS(BYFSYY),3,2)||DIGITS(BYFSPR) PERD, GRP, 
			SUM(BYQTY*CASE BYACTN WHEN 'I' THEN -1 ELSE 1 END) BYQTY
			SUM(BYQTY*CASE BYACTN WHEN 'I' THEN -1 ELSE 1 END*COALESCE(FCOST, STDCOST)) VALUE_LOCAL,
		FROM 
			LGDAT.STKT T
			LEFT OUTER JOIN RLARP.FFSTGR ON
				SRC = UPPER(RTRIM(BYSRC)||SUBSTRING(LTRIM(BYREAS||BYDREF),1,3))
			LEFT OUTER JOIN RLARP.FFCOSTEFFD ON
				PART = BYPART AND
				PLNT = BYPLNT AND
				CHAR(FDT)||' '||CHAR(FTM) < CHAR(BYSDAT)||' '||CHAR(BYSTIM) AND
				CHAR(TDT)||' '||CHAR(TTM) > CHAR(BYSDAT)||' '||CHAR(BYSTIM)
			LEFT OUTER JOIN RLARP.VW_FFICSTX ON
				V6PART = BYPART AND
				V6PLNT = BYPLNT
		WHERE
			BYFSYY = '2016' AND
			BYFSPR = '03'
		GROUP BY
			BYPART, BYPLNT, BYSTOK, SUBSTR(DIGITS(BYFSYY),3,2)||DIGITS(BYFSPR), GRP, COALESCE(FCOST, STDCOST)
		HAVING
			SUM(BYQTY*CASE BYACTN WHEN 'I' THEN -1 ELSE 1 END) <> 0
	) G
	INNER JOIN RLARP.VW_FFSTKMX ON
		AVPART = BYPART
	INNER JOIN LGDAT.PLNT ON
		YAPLNT = BYPLNT
	LEFT OUTER JOIN LGDAT.GLIE ON
		Y1GLEC = AVGLED AND
		Y1PLNT = BYPLNT
GROUP BY
	YACOMP||Y1INVA, PERD, GRP

UNION ALL

SELECT
	YACOMP||Y1INVA ACCT, 
	--PART, PLNT, PLNT, 
	FSPR, 'COST ROLL' GRP, 
	--TCOST - FCOST, TQTY
	SUM((TCOST - FCOST)* TQTY) VALUE_LOCAL
FROM
	RLARP.FFCOSTEFFD
	INNER JOIN LGDAT.PLNT ON
		YAPLNT = PLNT
	LEFT OUTER JOIN RLARP.VW_FFGLPD G ON
		G.COMP = YACOMP AND
		G.SDAT <= TDT AND
		G.EDAT >= TDT
	LEFT OUTER JOIN RLARP.VW_FFSTKMX ON
		AVPART = PART
	LEFT OUTER JOIN LGDAT.GLIE ON
		Y1PLNT = PLNT AND
		Y1GLEC = AVGLED
WHERE	
	FDT >= '2016-03-01' AND	
	FTM >= '00:00:00' AND
	TDT <= '2016-03-31' AND
	TTM <= '23:59:59' AND
	TQTY <> 0 AND
	TCOST <> FCOST
GROUP BY
	YACOMP||Y1INVA, 
	FSPR

UNION ALL

SELECT 
	YACOMP||Y1INVA ACCT, 
	CURRP,
	'OPEN' COMPONENT,
	ROUND(SUM(QTYOH*COST_EFF),2) VALUE_LOCAL	
FROM 
	RLARP.FFSTKBP 
	INNER JOIN LGDAT.PLNT ON
		YAPLNT = PLNT
	INNER JOIN RLARP.VW_PRFSPR ON
		COMP = YACOMP AND
		PRIORP = PERD
	LEFT OUTER JOIN RLARP.VW_FFSTKMX ON
		AVPART = PART
	LEFT OUTER JOIN LGDAT.GLIE ON
		Y1PLNT = PLNT AND
		Y1GLEC = AVGLED
WHERE
	CURRP = '1603'
GROUP BY
	YACOMP||Y1INVA, CURRP

UNION ALL

SELECT 
	YACOMP||Y1INVA ACCT, 
	PERD,
	'END' COMPONENT,
	ROUND(SUM(QTYOH*COST_EFF),2) VALUE_LOCAL	
FROM 
	RLARP.FFSTKBP 
	INNER JOIN LGDAT.PLNT ON
		YAPLNT = PLNT
	LEFT OUTER JOIN RLARP.VW_FFSTKMX ON
		AVPART = PART
	LEFT OUTER JOIN LGDAT.GLIE ON
		Y1PLNT = PLNT AND
		Y1GLEC = AVGLED
WHERE
	PERD = '1603'
GROUP BY
	YACOMP||Y1INVA, PERD
	