CREATE OR REPLACE VIEW RLARP.VW_GLLCS AS
	SELECT  
		SUBSTR(ACCT,1,2) AS COMP,  
		SUBSTR(ACCT,3,2) PLNT,  
		ACCT,  
		SUBSTR(ACCT,7,4) PRIME,  
		AZTITL,  
		AZSTAT INACTIVE,  
		AZFUT3 GLCC,  
		RTRIM(D35DES3) ELIM_TYPE,  
		RTRIM(D35USR1) ELIM_REL,  
		RTRIM(D35USR2) ELIM_DFGRP,  
		SUBSTR(DIGITS(D35USR4),9,2) ELIM_CO,
		D.PERD FSPR,  
		CAPR,  
		SDAT, 
		EDAT, 
		SUBSTR(LTRIM(D35USR2)||AZGROP,1,7)||' - '||RTRIM(TL.BQ1TITL) FGRP,  
		CASE WHEN AZATYP <= 3 
			THEN 'BALANCE SHEET' 
			ELSE 'INCOME STATEMENT' 
		END STMT,  
		SUBSTR(SUBSTR(LTRIM(D35USR2)||AZGROP,1,7),1,1)||' - '||RTRIM(SUBSTR(A249,1,30)) LVL0,  
		CASE LENGTH(RTRIM(SUBSTR(LTRIM(D35USR2)||AZGROP,1,7)))  
			WHEN 3 THEN SUBSTR(TL.BQ1GRP,2,2)||' - '||RTRIM(TL.BQ1TITL)  
			ELSE SUBSTR(FA.BQ1GRP,2,2)||' - '||RTRIM(FA.BQ1TITL)  
		END LVL1,  
		CASE LENGTH(RTRIM(SUBSTR(LTRIM(D35USR2)||AZGROP,1,7)))  
			WHEN 3 THEN ''  
			WHEN 5 THEN SUBSTR(TL.BQ1GRP,4,2)||' - '||RTRIM(TL.BQ1TITL)  
			ELSE SUBSTR(FB.BQ1GRP,4,2)||' - '||RTRIM(FB.BQ1TITL)  
		END LVL2,  
		CASE LENGTH(RTRIM(SUBSTR(LTRIM(D35USR2)||AZGROP,1,7)))  
			WHEN 3 THEN ''  
			WHEN 5 THEN ''  
			ELSE SUBSTR(TL.BQ1GRP,6,2)||' - '||RTRIM(TL.BQ1TITL)  
		END LVL3,  
		MODULE,
		CUSMOD,
		CUSKEY1, CUSKEY1D, 
		CUSKEY2, CUSKEY2D, 
		CUSKEY3, CUSKEY3D, 
		CUSKEY4, CUSKEY4D,
		COALESCE(BTVEND, BVCUST)||' - '||COALESCE(BTNAME, BVNAME) PARTY,
		TDATE,
		RTRIM(D35DES1) EBITDA,  
		RTRIM(SUBSTR(ACCT,5,2)||CASE WHEN LENGTH(RTRIM(D35DES2)) >0 THEN ' - '||D35DES2 ELSE '' END) DEPARTMENT,  
		RTRIM(D35USR3) DEP_GRP,  
		AZFUT2 CURR,
		'NET' COMPONENT,
		AMT*RATE AMOUNT
	FROM
		RLARP.FFSBGLR1 D
		INNER JOIN LGDAT.MAST ON 
			DIGITS(AZCOMP)||DIGITS(AZGL#1)||DIGITS(AZGL#2) = D.ACCT
		LEFT OUTER JOIN LGDAT.GGTP ON 
			D35GCDE = AZFUT3 
		LEFT OUTER JOIN LGDAT.NAME N ON 
			SUBSTR(N.A7,7,1) = SUBSTR(LTRIM(D35USR2)||AZGROP,1,1) AND 
			SUBSTR(N.A7,1,1) = 'A' 
		LEFT OUTER JOIN LGDAT.FGRP TL ON
			TL.BQ1GRP = SUBSTR(LTRIM(D35USR2)||AZGROP,1,7) 
		LEFT OUTER JOIN LGDAT.FGRP FA ON 
			FA.BQ1GRP = SUBSTR(TL.BQ1GRP,1,3) AND 
			LENGTH(RTRIM(TL.BQ1GRP)) >=5 
		LEFT OUTER JOIN LGDAT.FGRP FB ON  
			FB.BQ1GRP = SUBSTR(TL.BQ1GRP,1,5) AND  
			LENGTH(RTRIM(TL.BQ1GRP)) >=7 
		LEFT OUTER JOIN RLARP.FFCRET X ON  
			X.PERD = D.PERD AND 
			X.FCUR = AZFUT2 AND 
			X.TCUR = 'US' AND  
			X.RTYP = CASE WHEN AZATYP <= 3 THEN 'ME' ELSE 'MA' END  
		LEFT OUTER JOIN RLARP.VW_FFGLPD ON  
			COMP = SUBSTR(ACCT,1,2) AND  
			FSPR = D.PERD
		LEFT OUTER JOIN LGDAT.VEND ON	
			BTVEND = CUSVEND
		LEFT OUTER JOIN LGDAT.CUST ON
			BVCUST = CUSCUST
	WHERE  
		SUBSTR(ACCT,1,2) > '19';

LABEL ON TABLE RLARP.VW_GLLCS IS 'Acct - Ledger Activity - Logical Consolidation';

LABEL ON COLUMN RLARP.VW_GLLCS ( 
		COMP  TEXT IS 'Company',  
		PLNT  TEXT IS 'Plant',  
		ACCT  TEXT IS 'Account',  
		PRIME  TEXT IS 'Prime',  
		AZTITL  TEXT IS 'Account Title',  
		INACTIVE  TEXT IS 'Status',  
		GLCC  TEXT IS 'GL Category Code',  
		ELIM_TYPE  TEXT IS 'Elimiation Type',  
		ELIM_REL  TEXT IS 'Elimination Relationship',  
		ELIM_DFGRP  TEXT IS 'Elimination Destination Account Group',  
		ELIM_CO  TEXT IS 'Elimination Company',
		FSPR  TEXT IS 'F TEXT IScal Period',  
		CAPR   TEXT IS 'Calendar Period',  
		SDAT  TEXT IS'Start Date', 
		EDAT  TEXT IS'End Date', 
		FGRP  TEXT IS'Account Group',  
		STMT  TEXT IS'Statement',  
		LVL0  TEXT IS'Level 0',  
		LVL1  TEXT IS'Level 1',  
		LVL2  TEXT IS 'Level 2',  
		LVL3  TEXT IS 'Level 3',  
		MODULE  TEXT IS 'Module',
		CUSMOD  TEXT IS 'Custom Module',
		CUSKEY1  TEXT IS 'Custom Key 1', 
		CUSKEY1D  TEXT IS 'Custom Key 1 Type', 
		CUSKEY2  TEXT IS 'Custom Key 2', 
		CUSKEY2D  TEXT IS 'Custom Key 2 Type', 
		CUSKEY3  TEXT IS 'Custom Key 3', 
		CUSKEY3D  TEXT IS 'Custom Key 3 Type', 
		CUSKEY4  TEXT IS 'Custom Key 4', 
		CUSKEY4D  TEXT IS 'Custom Key 4 Type',
		EBITDA  TEXT IS 'EBITDA Categorization',  
		DEPARTMENT  TEXT IS 'Department & Description',  
		DEP_GRP  TEXT IS 'Department Group',  
		CURR  TEXT IS 'Local Curreny',
		COMPONENT  TEXT IS 'Roll-Forward Component',
		AMOUNT  TEXT IS 'Amount in USD'
);